-- ── Seed Data: tourism_villages ──────────────────────────────
INSERT INTO directory.tourism_villages (
  slug, name, destination_id, cover_image, description,
  featured, adwi_level_id, village_theme_id, rating_average, reviews_count,
  homestay_count, homestay_min_price,   max_daily_visitor, signature,
  activities,
  categories,
  location_address, location_accessibility, location_directions, location_latitude, location_longitude
) VALUES
  (
    'desa-wae-rebo', 'Desa Wae Rebo', '5315',
    '{"url": "https://images.unsplash.com/photo-1570214476695-19bd467e6f7a?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa adat terpencil di pegunungan Manggarai dengan rumah adat kerucut Mbaru Niang yang legendaris.", "en": "A remote traditional village in the Manggarai mountains featuring the legendary conical Mbaru Niang houses."}'::jsonb,
    true, (SELECT id FROM directory.taxonomies WHERE slug = 'mandiri' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.95, 245,
    7, 350000, 50, 'Mbaru Niang',
    '{tarian,workshop,homestay}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Satarmese Barat, Kabupaten Manggarai, Nusa Tenggara Timur", "en": "West Satarmese District, Manggarai Regency, East Nusa Tenggara"}'::jsonb,
    '{"id": "Terletak di pegunungan terpencil. Akses jalan aspal hanya sampai ke pos Denge, dilanjutkan dengan trekking mendaki bukit terjal hutan hujan sekitar 2-3 jam. Tidak ramah kursi roda.", "en": "Located in remote highlands. Road access only reaches Denge post, followed by a steep rainforest uphill trek of about 2-3 hours. Not wheelchair accessible."}'::jsonb,
    '[{"title": {"id": "Labuan Bajo → Pos Denge", "en": "Labuan Bajo → Denge Post"}, "detail": {"id": "Perjalanan darat sewa mobil ~4-5 jam melewati jalan berkelok lintas Flores.", "en": "Overland trip by rented car ~4-5 hours passing winding Flores roads."}}, {"title": {"id": "Pos Denge → Pos Registrasi Wae Rebo", "en": "Denge Post → Wae Rebo Registration Post"}, "detail": {"id": "Berjalan kaki menyusuri jalan setapak menanjak sejauh ~4.5 km.", "en": "Walk along the uphill footpath for ~4.5 km."}}]'::jsonb,
    -8.7758, 120.2831
  ),
  (
    'desa-penglipuran', 'Desa Penglipuran', '5104',
    '{"url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Salah satu desa paling bersih di dunia dengan tata ruang adat Bali kuno yang sangat asri dan tertata rapi.", "en": "One of the cleanest villages in the world boasting pristine ancient Balinese traditional layout and architecture."}'::jsonb,
    true, (SELECT id FROM directory.taxonomies WHERE slug = 'mandiri' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.88, 512,
    76, 200000, 300, 'Pekarangan seragam',
    '{workshop,homestay}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Bangli, Kabupaten Bangli, Bali", "en": "Bangli District, Bangli Regency, Bali"}'::jsonb,
    '{"id": "Sangat ramah disabilitas. Seluruh area jalan desa dilapisi paving block datar tanpa tanjakan terjal, bebas kendaraan bermotor.", "en": "Very wheelchair friendly. The entire village paths are paved flat block, with no steep climbs, and completely motor vehicle free."}'::jsonb,
    '[{"title": {"id": "Bandara Ngurah Rai → Bangli", "en": "Ngurah Rai Airport → Bangli"}, "detail": {"id": "Berkendara ke utara melewati Ubud atau Bypass Ida Bagus Mantra ~1.5 jam.", "en": "Drive north passing Ubud or Ida Bagus Mantra Bypass ~1.5 hours."}}, {"title": {"id": "Tempat Parkir → Gerbang Desa", "en": "Parking Lot → Village Gate"}, "detail": {"id": "Berjalan kaki sejauh 100 meter ke pintu masuk utama desa.", "en": "Walk 100 meters to the main entrance of the village."}}]'::jsonb,
    -8.4326, 115.3582
  ),
  (
    'desa-nglanggeran', 'Desa Nglanggeran', '3404',
    '{"url": "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa wisata terbaik ASEAN dengan keunikan situs Gunung Api Purba dan budidaya cokelat lokal.", "en": "Best ASEAN tourism village featuring the unique Ancient Volcano site and local cocoa farming tours."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'alam' AND type = 'village_theme'), 4.82, 189,
    38, 175000, 150, 'Gunung api purba',
    '{trekking,homestay}'::text[],
    '{alam}'::text[],
    '{"id": "Kecamatan Patuk, Kabupaten Gunungkidul, DI Yogyakarta", "en": "Patuk District, Gunungkidul Regency, DI Yogyakarta"}'::jsonb,
    '{"id": "Kawasan desa berbukit-bukit. Akses ke puncak gunung api purba berupa jalur trekking tanah dan batuan terjal berundak yang tidak ramah disabilitas.", "en": "Hilly village terrain. Access to the summit of the ancient volcano is via steep dirt and rock trekking paths not suitable for disabled access."}'::jsonb,
    '[{"title": {"id": "Yogyakarta → Patuk", "en": "Yogyakarta → Patuk"}, "detail": {"id": "Melewati Jl. Wonosari naik ke arah bukit Patuk ~45 menit.", "en": "Via Wonosari St. driving up towards Patuk hill ~45 minutes."}}, {"title": {"id": "Patuk → Nglanggeran", "en": "Patuk → Nglanggeran"}, "detail": {"id": "Belok kiri di pertigaan GCD Patuk ikuti penunjuk jalan ~10 menit.", "en": "Turn left at GCD Patuk intersection, follow directions ~10 minutes."}}]'::jsonb,
    -7.8722, 110.5427
  ),
  (
    'desa-pemuteran', 'Desa Pemuteran', '5103',
    '{"url": "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa pesisir Bali barat yang mendunia berkat pelestarian terumbu karang berbasis teknologi Biorock.", "en": "West Bali coastal village globally acclaimed for its community-based Biorock technology coral reef conservation."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'bahari' AND type = 'village_theme'), 4.85, 134,
    24, 250000, 100, 'Bio-rock coral',
    '{snorkel,homestay}'::text[],
    '{bahari}'::text[],
    '{"id": "Kecamatan Gerokgak, Kabupaten Buleleng, Bali", "en": "Gerokgak District, Buleleng Regency, Bali"}'::jsonb,
    '{"id": "Sangat mudah diakses di tepi jalan raya utama Bali Utara. Area pantai landai berpasir hitam yang mudah dijelajahi.", "en": "Very accessible on the main North Bali highway. Flat sandy beachfront area that is easy to explore."}'::jsonb,
    '[{"title": {"id": "Denpasar → Singaraja → Pemuteran", "en": "Denpasar → Singaraja → Pemuteran"}, "detail": {"id": "Perjalanan darat memotong tengah pulau Bali ~3.5 jam.", "en": "Overland trip crossing the center of Bali island ~3.5 hours."}}]'::jsonb,
    -8.1481, 114.6292
  ),
  (
    'desa-pentingsari', 'Desa Pentingsari', '3404',
    '{"url": "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa wisata perintis di lereng Merapi dengan program interaksi budaya pedesaan dan pertanian tradisional.", "en": "Pioneering tourism village on the slopes of Merapi offering rural cultural interactions and traditional farming."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'mandiri' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'pertanian' AND type = 'village_theme'), 4.78, 98,
    48, 165000, 200, 'Sawah terasering',
    '{kuliner,homestay}'::text[],
    '{pertanian}'::text[],
    '{"id": "Kecamatan Cangkringan, Kabupaten Sleman, DI Yogyakarta", "en": "Cangkringan District, Sleman Regency, DI Yogyakarta"}'::jsonb,
    '{"id": "Area perumahan warga datar dan mudah diakses. Sebagian jalur persawahan berundak tanah liat yang licin saat hujan.", "en": "Residential areas are flat and easy to access. Some paddy field trails are terraced clay paths that get slippery when raining."}'::jsonb,
    '[{"title": {"id": "Yogyakarta → Cangkringan", "en": "Yogyakarta → Cangkringan"}, "detail": {"id": "Berkendara lurus ke utara menyusuri Jl. Kaliurang ~40 menit.", "en": "Drive straight north along Kaliurang St. ~40 minutes."}}]'::jsonb,
    -7.6433, 110.4394
  ),
  (
    'desa-sasak-sade', 'Desa Sasak Sade', '5202',
    '{"url": "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa adat suku Sasak Lombok yang mempertahankan rumah jerami beralas kotoran kerbau dan tradisi tenun ikat.", "en": "Sasak tribe traditional village in Lombok maintaining thatched houses with clay-dung floors and ikat weaving tradition."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'berkembang' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.70, 320,
    150, 0, 250, 'Rumah Sasak adat',
    '{tarian,workshop}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Pujut, Kabupaten Lombok Tengah, Nusa Tenggara Barat", "en": "Pujut District, Central Lombok Regency, West Nusa Tenggara"}'::jsonb,
    '{"id": "Akses jalan desa berupa undakan tanah berundak dan gang sempit beraspal. Sedikit menyulitkan pengguna kursi roda.", "en": "Village access is earthen steps and narrow paved alleyways. Slightly challenging for wheelchair users."}'::jsonb,
    '[{"title": {"id": "Bandara Lombok → Sade", "en": "Lombok Airport → Sade"}, "detail": {"id": "Berkendara ke arah selatan menuju pantai Kuta ~15 menit di tepi jalan utama.", "en": "Drive south towards Kuta beach ~15 minutes right along the main road."}}]'::jsonb,
    -8.8398, 116.2917
  ),
  (
    'desa-wisata-alam-endah', 'Desa Wisata Alam Endah', '3273',
    '{"url": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa agrowisata subur di kawasan wisata Ciwidey dikelilingi kebun strawberry dan kebun teh berhawa sejuk.", "en": "Fertile agrotourism village in the Ciwidey area surrounded by strawberry farms and cool highland tea plantations."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'pertanian' AND type = 'village_theme'), 4.75, 112,
    28, 175000, 150, 'Kawah Putih & Ranca Upas',
    '{kuliner,homestay}'::text[],
    '{pertanian}'::text[],
    '{"id": "Kecamatan Rancabali, Kabupaten Bandung, Jawa Barat", "en": "Rancabali District, Bandung Regency, West Java"}'::jsonb,
    '{"id": "Jalur aspal mulus masuk ke pusat desa. Ramah kendaraan roda empat dan bus sedang. Jalur ke kebun strawberry datar.", "en": "Smooth paved roads into the village center. Accessible by cars and mid-sized buses. Trails to strawberry farms are flat."}'::jsonb,
    '[{"title": {"id": "Bandung → Ciwidey → Rancabali", "en": "Bandung → Ciwidey → Rancabali"}, "detail": {"id": "Melewati tol Soreang-Pasir Koja dilanjutkan jalur arteri Soreang-Ciwidey ~1.5 jam.", "en": "Via Soreang-Pasir Koja toll followed by Soreang-Ciwidey arterial road ~1.5 hours."}}]'::jsonb,
    -7.1432, 107.3912
  ),
  (
    'desa-wisata-ciptagelar', 'Desa Wisata Ciptagelar', '3273',
    '{"url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Kampung adat Kasepuhan Banten Kidul yang memegang kuat adat bertani padi tradisional dan kemandirian pangan.", "en": "Traditional Kasepuhan Banten Kidul settlement firmly upholding ancestral paddy farming rituals and food self-sufficiency."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'mandiri' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.85, 76,
    12, 250000, 80, 'Kasepuhan adat Sunda',
    '{workshop,homestay}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Cisolok, Kabupaten Sukabumi, Jawa Barat", "en": "Cisolok District, Sukabumi Regency, West Java"}'::jsonb,
    '{"id": "Medan perbukitan sangat terjal berbatu. Direkomendasikan menggunakan kendaraan 4WD (Jip) untuk masuk ke desa. Sangat tidak ramah kursi roda.", "en": "Extremely steep and rocky mountainous terrain. 4WD vehicles (Jeep) are highly recommended to enter. Not wheelchair friendly."}'::jsonb,
    '[{"title": {"id": "Pelabuhan Ratu → Cisolok", "en": "Pelabuhan Ratu → Cisolok"}, "detail": {"id": "Berkendara ke arah barat menuju perbatasan Banten ~30 menit.", "en": "Drive west towards Banten border ~30 minutes."}}, {"title": {"id": "Cisolok → Ciptagelar", "en": "Cisolok → Ciptagelar"}, "detail": {"id": "Jalur berbatu tanah menanjak melintasi pegunungan Halimun ~1.5 jam.", "en": "Rocky uphill dirt track crossing Halimun mountains ~1.5 hours."}}]'::jsonb,
    -6.7925, 106.4912
  ),
  (
    'desa-wisata-kete-kesu', 'Desa Wisata Kete Kesu', '7326',
    '{"url": "https://images.unsplash.com/photo-1562605209-c1e2d6145b2a?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa adat Toraja yang terkenal dengan deretan tongkonan dan ukiran kayu khas, serta pemakaman di tebing batu yang dramatis.", "en": "Traditional Toraja village famous for its row of tongkonan houses and intricate wood carvings, along with dramatic cliffside burial sites."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.72, 87,
    15, 175000, 80, 'Tongkonan & Tebing Makam',
    '{tarian,workshop,homestay}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Sanggalangi, Kabupaten Toraja Utara, Sulawesi Selatan", "en": "Sanggalangi District, North Toraja Regency, South Sulawesi"}'::jsonb,
    '{"id": "Akses jalan aspal sempit berkelok mendaki perbukitan Toraja. Area makam tebing batu tidak ramah kursi roda.", "en": "Narrow winding paved road climbing Toraja hills. Cliff burial areas are not wheelchair accessible."}'::jsonb,
    '[{"title": {"id": "Makassar → Rantepao", "en": "Makassar → Rantepao"}, "detail": {"id": "Perjalanan darat ~8-10 jam melewati poros Maros-Toraja.", "en": "Overland trip ~8-10 hours via the Maros-Toraja highway."}}, {"title": {"id": "Rantepao → Kete Kesu", "en": "Rantepao → Kete Kesu"}, "detail": {"id": "Berkendara ke selatan ~15 menit di jalan utama Toraja.", "en": "Drive south ~15 minutes on the main Toraja road."}}]'::jsonb,
    -2.9686, 119.8931
  ),
  (
    'desa-batuan', 'Desa Batuan', '5104',
    '{"url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa seni lukis tradisional Bali yang melegenda dengan gaya Batuan yang mendunia, galeri lukisan, dan tari Barong.", "en": "Legendary Balinese traditional painting village famous for the world-renowned Batuan style, painting galleries, and Barong dance."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'kerajinan' AND type = 'village_theme'), 4.72, 132,
    35, 200000, 200, 'Seni lukis Batuan',
    '{workshop,homestay,tarian}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Sukawati, Kabupaten Gianyar, Bali", "en": "Sukawati District, Gianyar Regency, Bali"}'::jsonb,
    '{"id": "Akses sangat mudah di tepi jalan raya utama Gianyar-Sukawati. Jalan desa datar dan beraspal, ramah kursi roda.", "en": "Very accessible on the main Gianyar-Sukawati road. Village roads are flat and paved, wheelchair friendly."}'::jsonb,
    '[{"title": {"id": "Bandara Ngurah Rai → Batuan", "en": "Ngurah Rai Airport → Batuan"}, "detail": {"id": "Berkendara ke timur laut melewati Sanur ~45 menit.", "en": "Drive northeast via Sanur ~45 minutes."}}]'::jsonb,
    -8.5858, 115.2706
  ),
  (
    'desa-tenganan', 'Desa Tenganan', '5107',
    '{"url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa Bali Aga tertua di Karangasem yang melestarikan tenun ikat ganda Geringsing sebagai warisan budaya takbenda UNESCO.", "en": "The oldest Bali Aga village in Karangasem preserving Geringsing double ikat weaving as UNESCO intangible cultural heritage."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'mandiri' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.78, 98,
    22, 225000, 120, 'Tenun ikat Geringsing',
    '{workshop,homestay,tarian}'::text[],
    '{budaya,heritage}'::text[],
    '{"id": "Kecamatan Manggis, Kabupaten Karangasem, Bali", "en": "Manggis District, Karangasem Regency, Bali"}'::jsonb,
    '{"id": "Jalan desa sebagian paving block datar. Beberapa anak tangga di area permukiman adat menyulitkan kursi roda.", "en": "Village roads are mostly flat paved blocks. Some steps in the traditional settlement area hinder wheelchairs."}'::jsonb,
    '[{"title": {"id": "Denpasar → Candidasa", "en": "Denpasar → Candidasa"}, "detail": {"id": "Berkendara ke timur melewati jalur pantai timur Bali ~1,5 jam.", "en": "Drive east along the east coast route ~1.5 hours."}}, {"title": {"id": "Candidasa → Tenganan", "en": "Candidasa → Tenganan"}, "detail": {"id": "Belok ke utara di pertigaan Candidasa ikuti jalan desa ~10 menit.", "en": "Turn north at Candidasa junction, follow village road ~10 minutes."}}]'::jsonb,
    -8.3682, 115.6887
  ),
  (
    'desa-candirejo', 'Desa Candirejo', '3308',
    '{"url": "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa wisata perdesaan asri di kawasan Borobudur menawarkan naik andong dan menyusuri sawah dengan latar Candi Borobudur.", "en": "Picturesque rural tourism village in the Borobudur area offering horse cart rides through rice fields with Borobudur Temple as backdrop."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'mandiri' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.72, 145,
    55, 150000, 250, 'Andong & Borobudur',
    '{kuliner,homestay,trekking}'::text[],
    '{budaya,heritage}'::text[],
    '{"id": "Kecamatan Borobudur, Kabupaten Magelang, Jawa Tengah", "en": "Borobudur District, Magelang Regency, Central Java"}'::jsonb,
    '{"id": "Medan desa relatif datar, jalan aspal desa ramah untuk semua jenis kendaraan. Akses kursi roda terbatas di area persawahan.", "en": "Relatively flat village terrain, asphalt roads accessible for all vehicles. Wheelchair access limited in rice field areas."}'::jsonb,
    '[{"title": {"id": "Yogyakarta → Borobudur", "en": "Yogyakarta → Borobudur"}, "detail": {"id": "Berkendara ke barat laut melewati Jalan Magelang ~1,5 jam.", "en": "Drive northwest via Magelang road ~1.5 hours."}}, {"title": {"id": "Borobudur → Candirejo", "en": "Borobudur → Candirejo"}, "detail": {"id": "Dari pintu masuk Candi Borobudur ikuti jalan ke timur ~5 menit.", "en": "From Borobudur temple entrance follow road east ~5 minutes."}}]'::jsonb,
    -7.6044, 110.2089
  ),
  (
    'desa-pujon-kidul', 'Desa Pujon Kidul', '3573',
    '{"url": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa agrowisata modern di dataran tinggi Malang dengan cafe sawah, glamping, dan panorama pegunungan yang sejuk.", "en": "Modern agrotourism village in the Malang highlands featuring rice field cafes, glamping, and cool mountain panoramas."}'::jsonb,
    true, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'pertanian' AND type = 'village_theme'), 4.58, 203,
    45, 185000, 300, 'Cafe sawah & glamping',
    '{kuliner,homestay}'::text[],
    '{pertanian,ecotourism}'::text[],
    '{"id": "Kecamatan Pujon, Kabupaten Malang, Jawa Timur", "en": "Pujon District, Malang Regency, East Java"}'::jsonb,
    '{"id": "Akses jalan aspal baik menuju kawasan cafe sawah. Area parkir luas. Beberapa jalur bebatuan di area glamping.", "en": "Good asphalt road access to cafe area. Spacious parking. Some rocky paths in glamping area."}'::jsonb,
    '[{"title": {"id": "Malang → Pujon", "en": "Malang → Pujon"}, "detail": {"id": "Berkendara ke utara melewati Jl. Raya Batu-Pujon ~45 menit.", "en": "Drive north via Batu-Pujon main road ~45 minutes."}}]'::jsonb,
    -7.8733, 112.4758
  ),
  (
    'desa-gubugklakah', 'Desa Gubugklakah', '3573',
    '{"url": "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa di lereng Gunung Bromo yang menjadi pusat paralayang dan wisata petualangan dengan kebun apel yang luas.", "en": "Village on the slopes of Mount Bromo serving as a paragliding hub and adventure tourism spot with vast apple orchards."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'berkembang' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'alam' AND type = 'village_theme'), 4.45, 76,
    18, 200000, 100, 'Paralayang Bukit Banyak',
    '{trekking,homestay}'::text[],
    '{alam,petualangan}'::text[],
    '{"id": "Kecamatan Poncokusumo, Kabupaten Malang, Jawa Timur", "en": "Poncokusumo District, Malang Regency, East Java"}'::jsonb,
    '{"id": "Medan perbukitan terjal dengan jalan aspal sempit berkelok. Lokasi lepas landas paralayang hanya dapat dijangkau trek kaki atau motor.", "en": "Steep hilly terrain with narrow winding asphalt road. Paragliding takeoff spot accessible only by foot or motorcycle."}'::jsonb,
    '[{"title": {"id": "Malang → Tumpang → Poncokusumo", "en": "Malang → Tumpang → Poncokusumo"}, "detail": {"id": "Berkendara ke timur melewati Tumpang ~1 jam.", "en": "Drive east via Tumpang ~1 hour."}}]'::jsonb,
    -7.9450, 112.6800
  ),
  (
    'desa-wringinputih', 'Desa Wringinputih', '3510',
    '{"url": "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa pesisir Banyuwangi dengan panorama Pulau Merah yang ikonis, surga berselancar dan snorkeling yang masih asri.", "en": "Coastal Banyuwangi village with the iconic Pulau Merah panorama, a pristine surfing and snorkeling paradise."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'bahari' AND type = 'village_theme'), 4.62, 64,
    14, 250000, 150, 'Pulau Merah & surfing',
    '{snorkel,homestay,kuliner}'::text[],
    '{bahari}'::text[],
    '{"id": "Kecamatan Muncar, Kabupaten Banyuwangi, Jawa Timur", "en": "Muncar District, Banyuwangi Regency, East Java"}'::jsonb,
    '{"id": "Akses jalan aspal mulus hingga pesisir pantai. Area parkir luas di tepi pantai berpasir putih.", "en": "Smooth asphalt road to the coast. Wide parking area by the white sandy beach."}'::jsonb,
    '[{"title": {"id": "Banyuwangi → Muncar → Pulau Merah", "en": "Banyuwangi → Muncar → Pulau Merah"}, "detail": {"id": "Berkendara ke selatan melewati pesisir ~1 jam.", "en": "Drive south along the coast ~1 hour."}}]'::jsonb,
    -8.5039, 114.0000
  ),
  (
    'desa-osing', 'Desa Osing', '3510',
    '{"url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Kampung adat suku Osing di Banyuwangi dengan rumah tradisional limasan dan tarian Gandrung yang memukau.", "en": "Traditional Osing tribe village in Banyuwangi featuring limasan traditional houses and the captivating Gandrung dance."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'rintisan' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.30, 42,
    10, 125000, 80, 'Tradisi Osing & Gandrung',
    '{tarian,workshop,homestay,kuliner}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Glagah, Kabupaten Banyuwangi, Jawa Timur", "en": "Glagah District, Banyuwangi Regency, East Java"}'::jsonb,
    '{"id": "Jalan desa paving block datar. Trase jalan sempit yang dapat dilalui kendaraan kecil.", "en": "Flat paved block village roads. Narrow streets passable by small vehicles."}'::jsonb,
    '[{"title": {"id": "Banyuwangi → Glagah → Kemiren", "en": "Banyuwangi → Glagah → Kemiren"}, "detail": {"id": "Berkendara ke arah utara lereng Gunung Ijen ~30 menit.", "en": "Drive north towards Mount Ijen slope ~30 minutes."}}]'::jsonb,
    -8.4117, 114.3394
  ),
  (
    'desa-tomok', 'Desa Tomok', '1212',
    '{"url": "https://images.unsplash.com/photo-1570214476695-19bd467e6f7a?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa adat Batak Toba di tepi Danau Toba yang terkenal dengan patung Sigale-gale, makam raja, dan ulos.", "en": "Batak Toba traditional village on the shores of Lake Toba famous for Sigale-gale puppet, king''s tomb, and ulos weaving."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'berkembang' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.42, 112,
    28, 150000, 200, 'Sigale-gale & Ulos Batak',
    '{homestay,kuliner,tarian}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Simanindo, Kabupaten Samosir, Sumatera Utara", "en": "Simanindo District, Samosir Regency, North Sumatra"}'::jsonb,
    '{"id": "Jalan aspal mengitari Danau Toba. Medan desa berbukit dengan beberapa anak tangga ke area makam raja.", "en": "Asphalt road circling Lake Toba. Hilly village terrain with steps to the king''s tomb area."}'::jsonb,
    '[{"title": {"id": "Medan → Parapat", "en": "Medan → Parapat"}, "detail": {"id": "Berkendara ke selatan via Tol Medan-Tebing Tinggi ~3 jam.", "en": "Drive south via Medan-Tebing Tinggi toll ~3 hours."}}, {"title": {"id": "Parapat → Tomok (feri)", "en": "Parapat → Tomok (ferry)"}, "detail": {"id": "Naik feri penyeberangan Danau Toba ~45 menit.", "en": "Take the Lake Toba ferry crossing ~45 minutes."}}]'::jsonb,
    2.6802, 98.8437
  ),
  (
    'desa-nagari-sianok-anau', 'Desa Nagari Sianok Anau', '1375',
    '{"url": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa wisata di tepi Lembah Sianok Bukittinggi dengan pemandangan ngarai spektakuler dan budaya Minangkabau.", "en": "Tourism village on the edge of Bukittinggi''s Sianok Valley offering spectacular canyon views and Minangkabau culture."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'berkembang' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'alam' AND type = 'village_theme'), 4.35, 55,
    12, 175000, 100, 'Lembah Sianok & Panorama',
    '{trekking,homestay,kuliner}'::text[],
    '{alam}'::text[],
    '{"id": "Kecamatan IV Koto, Kabupaten Agam, Sumatera Barat", "en": "IV Koto District, Agam Regency, West Sumatra"}'::jsonb,
    '{"id": "Jalan aspal berkelok dengan pemandangan lembah. Tidak ramah kursi roda karena kontur curam.", "en": "Winding asphalt road with valley views. Not wheelchair friendly due to steep terrain."}'::jsonb,
    '[{"title": {"id": "Padang → Bukittinggi", "en": "Padang → Bukittinggi"}, "detail": {"id": "Melewati jalur lintas Sumatera ~3 jam.", "en": "Via the Trans-Sumatra highway ~3 hours."}}, {"title": {"id": "Bukittinggi → Sianok Anau", "en": "Bukittinggi → Sianok Anau"}, "detail": {"id": "Berkendara ke selatan kota menuju tepi Lembah Sianok ~15 menit.", "en": "Drive south of the city towards Sianok Valley edge ~15 minutes."}}]'::jsonb,
    -0.3150, 100.3700
  ),
  (
    'desa-pulisan', 'Desa Pulisan', '7171',
    '{"url": "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa bahari di Likupang dengan pasir putih Pulau Lihaga, spot snorkeling kelas dunia, dan sunset yang magis.", "en": "Marine village in Likupang with the white sands of Lihaga Island, world-class snorkeling spots, and magical sunsets."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'rintisan' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'bahari' AND type = 'village_theme'), 4.28, 38,
    8, 200000, 60, 'Pulau Lihaga & snorkeling',
    '{snorkel,homestay}'::text[],
    '{bahari}'::text[],
    '{"id": "Kecamatan Likupang Timur, Kabupaten Minahasa Utara, Sulawesi Utara", "en": "East Likupang District, North Minahasa Regency, North Sulawesi"}'::jsonb,
    '{"id": "Jalan aspal mulus menuju area wisata bahari Likupang. Area pantai berpasir putih landai ramah pengunjung.", "en": "Smooth asphalt road to Likupang coastal area. White sandy beach with gentle slope."}'::jsonb,
    '[{"title": {"id": "Manado → Likupang", "en": "Manado → Likupang"}, "detail": {"id": "Berkendara ke timur laut melewati jalan pesisir ~1,5 jam.", "en": "Drive northeast along coastal road ~1.5 hours."}}]'::jsonb,
    1.5400, 124.9500
  ),
  (
    'desa-liang-ndara', 'Desa Liang Ndara', '5315',
    '{"url": "https://images.unsplash.com/photo-1570214476695-19bd467e6f7a?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa wisata alam di Manggarai Barat dengan gua batu cermin, bukit cinta, dan savana kering khas Flores.", "en": "Nature tourism village in West Manggarai featuring Mirror Stone Cave, Love Hill, and typical Flores dry savanna."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'berkembang' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'alam' AND type = 'village_theme'), 4.38, 47,
    11, 225000, 70, 'Gua Batu Cermin & Bukit Cinta',
    '{trekking,homestay}'::text[],
    '{alam,ecotourism}'::text[],
    '{"id": "Kecamatan Komodo, Kabupaten Manggarai Barat, Nusa Tenggara Timur", "en": "Komodo District, West Manggarai Regency, East Nusa Tenggara"}'::jsonb,
    '{"id": "Jalan tanah berbatu menuju kawasan karst. Sangat tidak ramah kursi roda. Disarankan trekking dipandu warga lokal.", "en": "Rocky dirt road to the karst area. Not wheelchair friendly. Guided trekking by locals recommended."}'::jsonb,
    '[{"title": {"id": "Labuan Bajo → Liang Ndara", "en": "Labuan Bajo → Liang Ndara"}, "detail": {"id": "Berkendara ke arah timur melewati Bandara ~30 menit.", "en": "Drive east past the airport ~30 minutes."}}]'::jsonb,
    -8.5600, 119.8900
  ),
  (
    'desa-pinge', 'Desa Pinge', '5103',
    '{"url": "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa budaya Badung yang melestarikan sistem irigasi subak khas Bali dan arsitektur Bali Aga yang autentik.", "en": "Badung cultural village preserving the unique Balinese subak irrigation system and authentic Bali Aga architecture."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.60, 89,
    25, 250000, 130, 'Subak & arsitektur Bali Aga',
    '{homestay,workshop,tarian,kuliner}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Mengwi, Kabupaten Badung, Bali", "en": "Mengwi District, Badung Regency, Bali"}'::jsonb,
    '{"id": "Akses mudah dari pusat wisata Seminyak dan Canggu. Jalan desa beraspal datar yang ramah kendaraan.", "en": "Easy access from Seminyak and Canggu tourist areas. Paved flat village roads."}'::jsonb,
    '[{"title": {"id": "Denpasar → Pinge", "en": "Denpasar → Pinge"}, "detail": {"id": "Berkendara ke barat laut melewati Seminyak ~30 menit.", "en": "Drive northwest via Seminyak ~30 minutes."}}]'::jsonb,
    -8.5167, 115.1667
  ),
  (
    'desa-tembi', 'Desa Tembi', '3471',
    '{"url": "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa budaya Yogyakarta yang menjadi pusat galeri seni joglo, workshop batik, dan pertunjukan wayang kulit.", "en": "Yogyakarta cultural village serving as a center for joglo art galleries, batik workshops, and wayang kulit performances."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'maju' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'budaya' AND type = 'village_theme'), 4.55, 78,
    20, 200000, 120, 'Galeri joglo & workshop batik',
    '{workshop,homestay,kuliner}'::text[],
    '{budaya}'::text[],
    '{"id": "Kecamatan Sewon, Kabupaten Bantul, DI Yogyakarta", "en": "Sewon District, Bantul Regency, DI Yogyakarta"}'::jsonb,
    '{"id": "Jalan aspal datar di area perumahan. Akses mudah dari pusat kota Yogyakarta dengan transportasi umum.", "en": "Flat paved roads in residential area. Easy access from Yogyakarta city center by public transport."}'::jsonb,
    '[{"title": {"id": "Yogyakarta → Tembi", "en": "Yogyakarta → Tembi"}, "detail": {"id": "Berkendara ke selatan melewati Jl. Parangtritis ~20 menit.", "en": "Drive south via Parangtritis St. ~20 minutes."}}]'::jsonb,
    -7.8197, 110.3669
  ),
  (
    'desa-brayut', 'Desa Brayut', '3404',
    '{"url": "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa pertanian organik Sleman yang memberdayakan petani lokal dengan wisata edukasi pertanian dan saung sawah.", "en": "Sleman organic farming village empowering local farmers with agricultural education tours and paddy field pavilions."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'berkembang' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'pertanian' AND type = 'village_theme'), 4.33, 56,
    30, 140000, 160, 'Pertanian organik & saung sawah',
    '{kuliner,homestay}'::text[],
    '{pertanian}'::text[],
    '{"id": "Kecamatan Sleman, Kabupaten Sleman, DI Yogyakarta", "en": "Sleman District, Sleman Regency, DI Yogyakarta"}'::jsonb,
    '{"id": "Jalan desa paving block dengan persawahan. Akses kursi roda terbatas di area pematang sawah.", "en": "Paved block village roads passing through rice fields. Wheelchair access limited on paddy dikes."}'::jsonb,
    '[{"title": {"id": "Yogyakarta → Sleman → Brayut", "en": "Yogyakarta → Sleman → Brayut"}, "detail": {"id": "Berkendara ke utara melewati Jl. Magelang ~30 menit.", "en": "Drive north via Magelang St. ~30 minutes."}}]'::jsonb,
    -7.6983, 110.4031
  ),
  (
    'desa-arborek', 'Desa Arborek', '9108',
    '{"url": "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa wisata bahari di Raja Ampat dengan dermaga berbentuk bintang, homestay tepi laut, dan snorkeling di taman laut terkaya di dunia.", "en": "Marine tourism village in Raja Ampat featuring a star-shaped jetty, beachfront homestays, and snorkeling in the world''s richest marine park."}'::jsonb,
    true, (SELECT id FROM directory.taxonomies WHERE slug = 'rintisan' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'bahari' AND type = 'village_theme'), 4.78, 42,
    8, 300000, 50, 'Dermaga bintang & taman laut',
    '{snorkel,homestay}'::text[],
    '{bahari}'::text[],
    '{"id": "Distrik Meos Mansar, Kabupaten Raja Ampat, Papua Barat Daya", "en": "Meos Mansar District, Raja Ampat Regency, Southwest Papua"}'::jsonb,
    '{"id": "Pulau kecil hanya dapat diakses perahu dari Waisai ~45 menit. Berjalan kaki menyusuri dermaga kayu sepanjang pulau.", "en": "Small island accessible only by boat from Waisai ~45 minutes. Walking along wooden jetty across the island."}'::jsonb,
    '[{"title": {"id": "Sorong → Waisai", "en": "Sorong → Waisai"}, "detail": {"id": "Feri cepat dari Sorong ke Waisai ~2 jam.", "en": "Fast ferry from Sorong to Waisai ~2 hours."}}, {"title": {"id": "Waisai → Arborek", "en": "Waisai → Arborek"}, "detail": {"id": "Perahu motor dari Pelabuhan Waisai ~45 menit.", "en": "Motorboat from Waisai harbor ~45 minutes."}}]'::jsonb,
    -0.5077, 130.4422
  ),
  (
    'desa-yenbekaki', 'Desa Yenbekaki', '9471',
    '{"url": "https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&auto=format&fit=crop&q=60"}'::jsonb,
    '{"id": "Desa tepi Danau Sentani di Papua dengan rumah panggung tradisional, tarian Yospan, dan kerajinan lukisan kulit kayu.", "en": "Lakeside village on Lake Sentani in Papua featuring traditional stilt houses, Yospan dance, and bark painting crafts."}'::jsonb,
    false, (SELECT id FROM directory.taxonomies WHERE slug = 'rintisan' AND type = 'adwi_level'), (SELECT id FROM directory.taxonomies WHERE slug = 'bahari' AND type = 'village_theme'), 4.18, 31,
    7, 200000, 60, 'Danau Sentani & lukisan kulit kayu',
    '{snorkel,homestay,kuliner}'::text[],
    '{bahari,budaya}'::text[],
    '{"id": "Kecamatan Sentani Timur, Kabupaten Jayapura, Papua", "en": "East Sentani District, Jayapura Regency, Papua"}'::jsonb,
    '{"id": "Area tepi Danau Sentani dengan akses jalan aspal. Dermaga kayu apung terapung yang tidak stabil untuk kursi roda.", "en": "Lake Sentani area with asphalt road access. Floating wooden jetties that are unstable for wheelchairs."}'::jsonb,
    '[{"title": {"id": "Jayapura → Sentani", "en": "Jayapura → Sentani"}, "detail": {"id": "Berkendara ke barat menuju Bandara Sentani ~45 menit.", "en": "Drive west towards Sentani Airport ~45 minutes."}}, {"title": {"id": "Sentani → Yenbekaki", "en": "Sentani → Yenbekaki"}, "detail": {"id": "Ikuti jalan lingkar tepi Danau Sentani ke arah timur ~20 menit.", "en": "Follow the lake ring road eastwards ~20 minutes."}}]'::jsonb,
    -2.6167, 140.6500
  )
ON CONFLICT (slug) DO NOTHING;

-- ── 2. Category Assignments ──────────────────────────────────


-- ── 3. Facility Assignments ──────────────────────────────────
INSERT INTO directory.facility_assignments (facility_id, entity_type, entity_id) VALUES
  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wae-rebo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wae-rebo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wae-rebo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wae-rebo')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'charging-station'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-penglipuran')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nglanggeran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nglanggeran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nglanggeran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nglanggeran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nglanggeran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nglanggeran')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pemuteran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pemuteran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pemuteran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pemuteran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pemuteran')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pemuteran')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pentingsari')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pentingsari')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pentingsari')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pentingsari')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pentingsari')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pentingsari')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-sasak-sade')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-sasak-sade')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-sasak-sade')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-sasak-sade')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-alam-endah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-alam-endah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-alam-endah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-alam-endah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-alam-endah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-alam-endah')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-ciptagelar')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-ciptagelar')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-ciptagelar')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-kete-kesu')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-kete-kesu')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-kete-kesu')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-kete-kesu')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-kete-kesu')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wisata-kete-kesu')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-batuan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-batuan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-batuan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-batuan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-batuan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-batuan')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tenganan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tenganan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tenganan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tenganan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tenganan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tenganan')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-candirejo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-candirejo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-candirejo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-candirejo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-candirejo')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-candirejo')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),
  ((SELECT id FROM directory.facilities WHERE slug = 'charging-station'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pujon-kidul')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-gubugklakah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-gubugklakah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-gubugklakah')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-gubugklakah')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wringinputih')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wringinputih')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wringinputih')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wringinputih')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-wringinputih')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-osing')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-osing')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-osing')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-osing')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-osing')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tomok')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tomok')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tomok')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tomok')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tomok')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tomok')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nagari-sianok-anau')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nagari-sianok-anau')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nagari-sianok-anau')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nagari-sianok-anau')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nagari-sianok-anau')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-nagari-sianok-anau')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pulisan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pulisan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pulisan')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pulisan')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-liang-ndara')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-liang-ndara')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-liang-ndara')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-liang-ndara')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pinge')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pinge')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pinge')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pinge')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pinge')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-pinge')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tembi')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tembi')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tembi')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tembi')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tembi')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-tembi')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-brayut')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-brayut')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-brayut')),
  ((SELECT id FROM directory.facilities WHERE slug = 'musholla'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-brayut')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-brayut')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-brayut')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-arborek')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-arborek')),
  ((SELECT id FROM directory.facilities WHERE slug = 'pemandu-lokal'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-arborek')),

  ((SELECT id FROM directory.facilities WHERE slug = 'toilet'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-yenbekaki')),
  ((SELECT id FROM directory.facilities WHERE slug = 'restoran'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-yenbekaki')),
  ((SELECT id FROM directory.facilities WHERE slug = 'parkir'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-yenbekaki')),
  ((SELECT id FROM directory.facilities WHERE slug = 'homestay'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-yenbekaki')),
  ((SELECT id FROM directory.facilities WHERE slug = 'wifi'), 'village', (SELECT id FROM directory.tourism_villages WHERE slug = 'desa-yenbekaki'));

-- Tourism village certifications (awards)
