/* Attraction Directory styles — from directory-styles.jsx + attraction-specific */
const dirStyles = {
  hero: {
    background: "linear-gradient(180deg, #F6F4FF 0%, #FFFFFF 100%)",
    borderBottom: "1px solid var(--atr-outline)",
    overflow: "hidden",
  },
  heroInner: {
    maxWidth: 1376,
    margin: "0 auto",
    padding: "56px 32px 48px",
    display: "grid",
    gridTemplateColumns: "1.05fr 1fr",
    gap: 64,
    alignItems: "center",
  },
  heroLeft: { display: "flex", flexDirection: "column", gap: 20 },
  heroTitle: {
    fontSize: 56,
    lineHeight: 1.05,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "var(--atr-text)",
    marginTop: 4,
  },
  heroSubtitle: {
    fontSize: 17,
    lineHeight: 1.55,
    color: "var(--atr-text-muted)",
    maxWidth: 520,
    marginTop: 4,
  },
  heroCtaRow: { display: "flex", gap: 12, marginTop: 8 },
  heroPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "var(--atr-purple)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "14px 22px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    boxShadow: "0 6px 16px rgba(112,104,213,0.3)",
  },
  heroSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    color: "var(--atr-text)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 10,
    padding: "14px 22px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  heroStats: {
    display: "flex",
    gap: 36,
    marginTop: 24,
    paddingTop: 24,
    borderTop: "1px dashed var(--atr-outline)",
  },
  stat: { display: "flex", flexDirection: "column", gap: 2 },
  statN: { fontSize: 26, fontWeight: 700, color: "var(--atr-purple)" },
  statL: { fontSize: 13, color: "var(--atr-text-muted)" },
  heroRight: { position: "relative", height: 460 },
  heroIllustrationCard: { position: "absolute", inset: 0, borderRadius: 24 },
  dayPill: {
    position: "absolute",
    top: 16,
    left: 16,
    zIndex: 3,
    background: "var(--atr-purple)",
    color: "#fff",
    fontSize: 12,
    fontWeight: 600,
    padding: "6px 12px",
    borderRadius: 999,
    boxShadow: "0 4px 12px rgba(112,104,213,0.4)",
  },
  heroImg1: {
    position: "absolute",
    inset: "20px 40px 20px 0",
    width: "calc(100% - 40px)",
    height: "calc(100% - 40px)",
    objectFit: "cover",
    borderRadius: 20,
    boxShadow: "0 20px 40px rgba(31,27,51,0.18)",
  },
  heroFloatCard: {
    position: "absolute",
    top: 70,
    left: -20,
    background: "#fff",
    borderRadius: 14,
    padding: "12px 14px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    boxShadow: "0 12px 28px rgba(31,27,51,0.16)",
    minWidth: 240,
    zIndex: 2,
  },
  heroFloatCard2: {
    position: "absolute",
    bottom: 50,
    left: 30,
    background: "#fff",
    borderRadius: 14,
    padding: "12px 14px",
    display: "flex",
    alignItems: "center",
    gap: 12,
    boxShadow: "0 12px 28px rgba(31,27,51,0.16)",
    minWidth: 280,
    zIndex: 2,
  },
  heroFloatTime: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--atr-purple)",
    background: "#EDE9FF",
    borderRadius: 8,
    padding: "6px 8px",
    minWidth: 44,
    textAlign: "center",
  },
  heroFloatTitle: { fontSize: 13, fontWeight: 600, color: "var(--atr-text)" },
  heroFloatMeta: { fontSize: 11, color: "var(--atr-text-muted)" },
  heroFloatTag: {
    fontSize: 10,
    fontWeight: 700,
    background: "#EDE9FF",
    color: "var(--atr-purple)",
    padding: "4px 8px",
    borderRadius: 999,
    marginLeft: "auto",
  },

  tabsBar: {
    background: "#fff",
    borderBottom: "1px solid var(--atr-outline)",
    position: "sticky",
    top: 71,
    zIndex: 40,
  },
  tabsInner: {
    maxWidth: 1376,
    margin: "0 auto",
    padding: "0 32px",
    display: "flex",
    gap: 8,
    overflowX: "auto",
  },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
    border: "none",
    padding: "18px 4px",
    fontSize: 15,
    fontWeight: 500,
    color: "var(--atr-text-muted)",
    cursor: "pointer",
    borderBottom: "3px solid transparent",
    marginRight: 24,
    fontFamily: "var(--atr-font-sans)",
  },
  tabActive: {
    color: "var(--atr-purple)",
    fontWeight: 700,
    borderBottom: "3px solid var(--atr-purple)",
  },
  tabCount: {
    fontSize: 11,
    fontWeight: 700,
    background: "var(--atr-bg-soft)",
    color: "var(--atr-text-muted)",
    padding: "2px 8px",
    borderRadius: 999,
  },
  tabCountActive: { background: "#EDE9FF", color: "var(--atr-purple)" },

  filterWrap: { maxWidth: 1376, margin: "0 auto", padding: "24px 32px 0" },
  filterRow: {
    display: "flex",
    gap: 20,
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  filterLeft: { display: "flex", gap: 8, flexWrap: "wrap" },
  filterChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: "10px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--atr-text)",
    fontFamily: "var(--atr-font-sans)",
    cursor: "pointer",
  },
  filterRight: { display: "flex", gap: 12, alignItems: "center" },
  viewToggle: {
    display: "inline-flex",
    background: "var(--atr-bg-soft)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: 3,
  },
  viewBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    border: "none",
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--atr-text-muted)",
    borderRadius: 999,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  viewBtnActive: {
    background: "#fff",
    color: "var(--atr-text)",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    fontWeight: 600,
  },
  sortBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 8,
    padding: "10px 14px",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--atr-text)",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  activeRow: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    marginTop: 16,
    paddingBottom: 16,
    borderBottom: "1px solid var(--atr-outline)",
    flexWrap: "wrap",
  },
  resultCount: { fontSize: 14, color: "var(--atr-text-muted)" },
  activeChips: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    alignItems: "center",
    marginLeft: "auto",
  },
  activeChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#EDE9FF",
    color: "var(--atr-purple)",
    fontSize: 12,
    fontWeight: 600,
    padding: "5px 10px",
    borderRadius: 999,
  },
  chipX: { cursor: "pointer", opacity: 0.7 },
  clearAll: {
    background: "transparent",
    border: "none",
    color: "var(--atr-text-muted)",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    textDecoration: "underline",
    fontFamily: "var(--atr-font-sans)",
  },
  dropdown: {
    position: "absolute",
    top: "calc(100% + 8px)",
    left: 0,
    zIndex: 30,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 12,
    boxShadow: "0 12px 32px rgba(31,27,51,0.12)",
    padding: 6,
    minWidth: 220,
    maxHeight: 320,
    overflowY: "auto",
  },
  dropdownItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    background: "transparent",
    border: "none",
    padding: "10px 12px",
    fontSize: 13,
    color: "var(--atr-text)",
    cursor: "pointer",
    borderRadius: 8,
    textAlign: "left",
    fontFamily: "var(--atr-font-sans)",
  },
  checkbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    border: "1.5px solid var(--atr-outline)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  checkboxOn: {
    background: "var(--atr-purple)",
    border: "1.5px solid var(--atr-purple)",
  },
  radio: {
    width: 14,
    height: 14,
    borderRadius: 999,
    border: "1.5px solid var(--atr-outline)",
    flexShrink: 0,
    position: "relative",
  },
  radioOn: {
    border: "1.5px solid var(--atr-purple)",
    boxShadow: "inset 0 0 0 3px var(--atr-purple)",
    background: "#fff",
  },

  /* Map view for itinerary page (included for completeness) */
  mapWrap: { maxWidth: 1376, margin: "32px auto 0", padding: "0 32px" },
  mapShell: {
    display: "grid",
    gridTemplateColumns: "1fr 1.4fr",
    gap: 0,
    border: "1px solid var(--atr-outline)",
    borderRadius: 16,
    overflow: "hidden",
    height: 640,
  },
  mapSidebar: {
    overflowY: "auto",
    background: "#fff",
    borderRight: "1px solid var(--atr-outline)",
  },
  mapSidebarHeader: {
    padding: "16px 20px",
    borderBottom: "1px solid var(--atr-outline)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    position: "sticky",
    top: 0,
    background: "#fff",
    zIndex: 2,
  },
  mapSidebarTitle: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)" },
  mapSidebarSub: { fontSize: 12, color: "var(--atr-text-muted)" },
  mapItem: {
    display: "grid",
    gridTemplateColumns: "100px 1fr",
    gap: 14,
    padding: 16,
    cursor: "pointer",
    borderBottom: "1px solid var(--atr-outline)",
    transition: "background .15s",
  },
  mapItemActive: { background: "#F6F4FF" },
  mapItemImg: { width: 100, height: 80, objectFit: "cover", borderRadius: 10 },
  mapCanvas: {
    position: "relative",
    background: "#E4E6F3",
    backgroundImage:
      "radial-gradient(circle at 20% 30%, #D4ECF4 0%, transparent 40%), radial-gradient(circle at 70% 60%, #E4E6F3 0%, transparent 50%), linear-gradient(135deg, #E8EAF5 0%, #DCE0F0 100%)",
    overflow: "hidden",
  },
  mapPin: {
    position: "absolute",
    transform: "translate(-50%, -100%)",
    cursor: "pointer",
    transition: "transform .15s",
  },
  mapPinActive: { zIndex: 2 },
  mapPinDot: {
    width: 32,
    height: 32,
    borderRadius: 999,
    background: "var(--atr-purple)",
    border: "3px solid #fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 12,
    fontWeight: 700,
    boxShadow: "0 4px 12px rgba(31,27,51,0.3)",
  },
  mapPinDotActive: {
    background: "var(--atr-yellow)",
    color: "#3D2900",
    transform: "scale(1.2)",
  },
  mapPinTail: {
    width: 0,
    height: 0,
    borderLeft: "6px solid transparent",
    borderRight: "6px solid transparent",
    borderTop: "8px solid #fff",
    margin: "0 auto",
    marginTop: -2,
  },
  mapPopup: {
    position: "absolute",
    bottom: 16,
    left: 16,
    background: "#fff",
    borderRadius: 12,
    padding: 12,
    boxShadow: "0 12px 28px rgba(31,27,51,0.18)",
    width: 280,
    display: "flex",
    gap: 12,
  },
  mapPopupImg: { width: 72, height: 72, objectFit: "cover", borderRadius: 8 },
  mapAttribution: {
    position: "absolute",
    bottom: 6,
    right: 8,
    fontSize: 10,
    color: "rgba(31,27,51,0.5)",
  },
};

const cardStyles = {
  gridSection: { maxWidth: 1376, margin: "0 auto", padding: "56px 32px 0" },
  gridHeader: { marginBottom: 24 },
  eyebrow: {
    fontSize: 13,
    fontWeight: 600,
    color: "var(--atr-purple)",
    marginBottom: 4,
  },
  railTitle: {
    fontSize: 28,
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--atr-text)",
  },
  rail: { maxWidth: 1376, margin: "0 auto", padding: "40px 32px 0" },
  railHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 24,
  },
  railLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "var(--atr-purple)",
    fontSize: 14,
    fontWeight: 600,
    textDecoration: "none",
  },
  railGrid: { display: "grid", gridTemplateColumns: "1.5fr 1fr", gap: 20 },
  railSide: { display: "grid", gridTemplateRows: "1fr 1fr", gap: 20 },
  featBig: {
    position: "relative",
    borderRadius: 20,
    overflow: "hidden",
    minHeight: 480,
    display: "flex",
    alignItems: "flex-end",
  },
  featBigImg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  featBigOverlay: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(180deg, rgba(31,27,51,0.0) 35%, rgba(31,27,51,0.85) 100%)",
  },
  featBigBadge: { position: "absolute", top: 20, left: 20 },
  editorBadge: {
    display: "inline-block",
    background: "var(--atr-yellow)",
    color: "#3D2900",
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.1em",
    padding: "6px 10px",
    borderRadius: 4,
  },
  saveTopRight: {
    position: "absolute",
    top: 16,
    right: 16,
    width: 38,
    height: 38,
    borderRadius: 999,
    background: "rgba(255,255,255,0.92)",
    backdropFilter: "blur(4px)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  featBigBody: {
    position: "relative",
    padding: 28,
    color: "#fff",
    width: "100%",
  },
  featBigMeta: { display: "flex", gap: 6, marginBottom: 14, flexWrap: "wrap" },
  featBigChip: {
    background: "rgba(255,255,255,0.18)",
    backdropFilter: "blur(8px)",
    color: "#fff",
    fontSize: 12,
    fontWeight: 600,
    padding: "5px 10px",
    borderRadius: 999,
  },
  featBigTitle: {
    fontSize: 28,
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: "-0.01em",
    marginBottom: 10,
  },
  featBigDesc: {
    fontSize: 14,
    lineHeight: 1.5,
    opacity: 0.85,
    marginBottom: 20,
    maxWidth: 540,
  },
  featBigFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 16,
    borderTop: "1px solid rgba(255,255,255,0.2)",
  },
  authorRow: { display: "flex", alignItems: "center", gap: 10 },
  authorImg: {
    width: 36,
    height: 36,
    borderRadius: 999,
    border: "2px solid rgba(255,255,255,0.4)",
  },
  featBigBudget: { textAlign: "right" },
  budgetLabel: { fontSize: 11, opacity: 0.7 },
  budgetVal: { fontSize: 22, fontWeight: 700 },
  budgetUnit: { fontSize: 12, fontWeight: 400, opacity: 0.7, marginLeft: 4 },
  featSmall: {
    background: "#fff",
    borderRadius: 16,
    overflow: "hidden",
    border: "1px solid var(--atr-outline)",
    display: "grid",
    gridTemplateColumns: "180px 1fr",
    minHeight: 230,
  },
  featSmallImgWrap: { position: "relative" },
  featSmallImg: { width: "100%", height: "100%", objectFit: "cover" },
  featSmallTag: {
    position: "absolute",
    top: 12,
    left: 12,
    background: "rgba(255,255,255,0.95)",
    color: "var(--atr-purple)",
    fontSize: 10,
    fontWeight: 700,
    padding: "4px 8px",
    borderRadius: 999,
    letterSpacing: "0.04em",
  },
  featSmallBody: {
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  featSmallDays: {
    fontSize: 12,
    color: "var(--atr-text-muted)",
    fontWeight: 600,
  },
  featSmallTitle: {
    fontSize: 17,
    fontWeight: 700,
    lineHeight: 1.25,
    color: "var(--atr-text)",
  },
  featSmallFooter: {
    marginTop: "auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 12,
    borderTop: "1px dashed var(--atr-outline)",
  },
  featSmallAuthor: { fontSize: 12, color: "var(--atr-text-muted)" },
  featSmallBudget: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--atr-purple)",
  },
  grid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 24 },
  card: {
    background: "#fff",
    borderRadius: 16,
    border: "1px solid var(--atr-outline)",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    transition: "transform .25s ease, box-shadow .25s ease",
  },
  cardImgWrap: {
    position: "relative",
    aspectRatio: "16 / 11",
    overflow: "hidden",
  },
  cardImg: { width: "100%", height: "100%", objectFit: "cover" },
  cardTag: {
    position: "absolute",
    top: 12,
    left: 12,
    background: "rgba(255,255,255,0.95)",
    color: "var(--atr-purple)",
    fontSize: 10,
    fontWeight: 700,
    padding: "5px 10px",
    borderRadius: 999,
    letterSpacing: "0.04em",
  },
  cardSave: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 34,
    height: 34,
    borderRadius: 999,
    background: "rgba(255,255,255,0.92)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    border: "none",
    zIndex: 2,
  },
  cardSaveOn: { background: "var(--atr-red)" },
  cardImgBottom: {
    position: "absolute",
    bottom: 10,
    left: 12,
    display: "flex",
    gap: 6,
  },
  cardDaysPill: {
    background: "rgba(31,27,51,0.8)",
    color: "#fff",
    fontSize: 10,
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },
  cardCityPill: {
    background: "rgba(255,255,255,0.92)",
    color: "var(--atr-text)",
    fontSize: 10,
    fontWeight: 600,
    padding: "4px 10px",
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },
  cardBody: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    flex: 1,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: 700,
    lineHeight: 1.25,
    color: "var(--atr-text)",
  },
  cardDayPreview: {
    fontSize: 12,
    color: "var(--atr-text-muted)",
    display: "flex",
    flexWrap: "wrap",
    gap: 4,
  },
  dayLabel: { fontWeight: 600, color: "var(--atr-text)" },
  dayPoint: {},
  dayDot: { color: "var(--atr-outline)" },
  cardFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: "auto",
    paddingTop: 12,
    borderTop: "1px dashed var(--atr-outline)",
  },
  cardAuthor: { display: "flex", alignItems: "center", gap: 8 },
  authorAvatar: {
    width: 30,
    height: 30,
    borderRadius: 999,
    background: "var(--atr-bg-soft)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    fontWeight: 700,
    color: "var(--atr-text)",
  },
  cardAuthorName: { fontSize: 12, fontWeight: 600, color: "var(--atr-text)" },
  cardAuthorRole: { fontSize: 10, color: "var(--atr-text-muted)" },
  cardMeta: {
    textAlign: "right",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  ratingRow: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: "var(--atr-text)",
    justifyContent: "flex-end",
  },
  reviewCount: { color: "var(--atr-text-muted)" },
  priceRow: {
    display: "flex",
    alignItems: "baseline",
    gap: 4,
    justifyContent: "flex-end",
  },
  priceFrom: { fontSize: 10, color: "var(--atr-text-muted)" },
  priceVal: { fontSize: 14, fontWeight: 700, color: "var(--atr-purple)" },
  paginationRow: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: 10,
    marginTop: 40,
  },
  loadMore: {
    background: "#fff",
    border: "1.5px solid var(--atr-purple)",
    color: "var(--atr-purple)",
    borderRadius: 10,
    padding: "12px 28px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  pageInfo: { fontSize: 12, color: "var(--atr-text-muted)" },

  /* CTA Band */
  ctaBand: {
    background: "linear-gradient(135deg, #6F66D5 0%, #524BAA 100%)",
    marginTop: 80,
    borderRadius: 24,
    maxWidth: 1376,
    marginLeft: "auto",
    marginRight: "auto",
    overflow: "hidden",
  },
  ctaInner: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 48,
    alignItems: "center",
    padding: "56px",
  },
  ctaLeft: { color: "#fff" },
  ctaTitle: {
    fontSize: 36,
    fontWeight: 700,
    lineHeight: 1.15,
    letterSpacing: "-0.01em",
    marginTop: 8,
    marginBottom: 14,
  },
  ctaSub: {
    fontSize: 15,
    opacity: 0.85,
    lineHeight: 1.55,
    marginBottom: 24,
    maxWidth: 480,
  },
  ctaBtnRow: { display: "flex", gap: 10 },
  ctaPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    color: "var(--atr-purple)",
    border: "none",
    borderRadius: 10,
    padding: "14px 22px",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  ctaSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "rgba(255,255,255,0.12)",
    color: "#fff",
    border: "1px solid rgba(255,255,255,0.25)",
    borderRadius: 10,
    padding: "14px 22px",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  builderCard: {
    background: "#fff",
    borderRadius: 18,
    padding: 22,
    boxShadow: "0 24px 48px rgba(0,0,0,0.18)",
  },
  builderHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: "1px solid var(--atr-outline)",
  },
  builderTitle: { fontSize: 16, fontWeight: 700, color: "var(--atr-text)" },
  builderTabs: { display: "flex", gap: 4 },
  builderTab: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--atr-text-muted)",
    padding: "5px 10px",
    borderRadius: 999,
    cursor: "pointer",
  },
  builderTabActive: { background: "#EDE9FF", color: "var(--atr-purple)" },
  builderActivities: { display: "flex", flexDirection: "column", gap: 14 },
  builderRow: {
    display: "grid",
    gridTemplateColumns: "44px 16px 1fr",
    gap: 8,
    alignItems: "center",
  },
  builderTime: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--atr-text-muted)",
  },
  builderDot: {
    position: "relative",
    width: 16,
    height: 28,
    display: "flex",
    justifyContent: "center",
  },
  builderInnerDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    background: "var(--atr-purple)",
    border: "2px solid #fff",
    boxShadow: "0 0 0 2px var(--atr-purple)",
  },
  builderLine: {
    position: "absolute",
    top: 14,
    bottom: -16,
    left: "50%",
    transform: "translateX(-50%)",
    width: 2,
    background: "var(--atr-purple-light)",
  },
  builderItem: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "var(--atr-bg-soft)",
    borderRadius: 10,
    padding: "10px 12px",
  },
  builderItemTitle: { fontSize: 13, fontWeight: 600, color: "var(--atr-text)" },
  builderItemTag: {
    fontSize: 10,
    fontWeight: 700,
    padding: "3px 8px",
    borderRadius: 999,
    marginLeft: 8,
  },
};

/* Attraction Hero specific styles */
const attrHero = {
  collage: { position: "absolute", inset: 0 },
  collageImg1: {
    position: "absolute",
    top: 20,
    right: 0,
    width: "62%",
    height: "60%",
    objectFit: "cover",
    borderRadius: 16,
    boxShadow: "0 16px 32px rgba(31,27,51,0.18)",
  },
  collageImg2: {
    position: "absolute",
    bottom: 24,
    left: 12,
    width: "48%",
    height: "44%",
    objectFit: "cover",
    borderRadius: 16,
    boxShadow: "0 12px 28px rgba(31,27,51,0.14)",
  },
  collageImg3: {
    position: "absolute",
    top: 130,
    left: 60,
    width: "32%",
    height: "38%",
    objectFit: "cover",
    borderRadius: 12,
    boxShadow: "0 10px 20px rgba(31,27,51,0.12)",
    border: "4px solid #fff",
  },
  floatStat: {
    position: "absolute",
    top: 30,
    left: -20,
    background: "#fff",
    borderRadius: 14,
    padding: "12px 16px",
    boxShadow: "0 12px 28px rgba(31,27,51,0.16)",
    zIndex: 3,
  },
  floatStatNum: {
    fontSize: 26,
    fontWeight: 700,
    color: "var(--atr-text)",
    lineHeight: 1,
  },
  floatStatLabel: {
    fontSize: 11,
    color: "var(--atr-text-muted)",
    maxWidth: 130,
    marginTop: 4,
  },
  floatCat: {
    position: "absolute",
    bottom: 60,
    right: -10,
    background: "#fff",
    borderRadius: 14,
    padding: "10px 14px",
    boxShadow: "0 12px 28px rgba(31,27,51,0.16)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    zIndex: 3,
  },
  floatCatIcon: {
    fontSize: 22,
    background: "#EDE9FF",
    borderRadius: 10,
    width: 40,
    height: 40,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  floatCatTitle: { fontSize: 13, fontWeight: 700, color: "var(--atr-text)" },
  floatCatMeta: { fontSize: 11, color: "var(--atr-text-muted)" },
};

export { dirStyles, cardStyles, attrHero };
