/* Card Component Styles — atomic styles for reusable card components */

const cs = {
  /* ─── ATTRACTION GRID ─── */
  atrGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 },
  atrCard: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 12,
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    transition: "transform .2s, box-shadow .2s",
    display: "flex",
    flexDirection: "column",
  },
  atrImgWrap: {
    position: "relative",
    aspectRatio: "4 / 3",
    overflow: "hidden",
  },
  atrCat: {
    position: "absolute",
    top: 10,
    right: 10,
    fontSize: 10,
    fontWeight: 700,
    padding: "4px 9px",
    borderRadius: 999,
    letterSpacing: "0.04em",
  },
  atrSave: {
    position: "absolute",
    top: 10,
    left: 10,
    width: 30,
    height: 30,
    background: "rgba(255,255,255,0.95)",
    border: "none",
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  atrBody: { padding: 14, display: "flex", flexDirection: "column", gap: 8, flex: 1 },
  atrName: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)", lineHeight: 1.3 },
  atrDesc: {
    fontSize: 12,
    color: "var(--atr-text-muted)",
    lineHeight: 1.5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  atrMeta: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 12,
    color: "var(--atr-text-muted)",
    marginTop: "auto",
    paddingTop: 8,
  },
  atrRating: { color: "var(--atr-text)", fontWeight: 700 },
  atrReviews: { color: "var(--atr-text-muted)" },
  atrLoc: { display: "flex", alignItems: "center", gap: 4, marginLeft: "auto", fontSize: 11 },
  atrFooter: {
    marginTop: "auto",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 10,
    borderTop: "1px dashed var(--atr-outline)",
  },
  atrPrice: { fontSize: 13, fontWeight: 700, color: "var(--atr-purple)" },
  atrCta: {
    background: "transparent",
    border: "none",
    color: "var(--atr-purple)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },

  /* ─── ATTRACTION LIST ─── */
  atrList: { display: "flex", flexDirection: "column", gap: 12 },
  atrListCard: {
    display: "flex",
    gap: 16,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    transition: "transform .2s, box-shadow .2s",
  },
  atrListImgWrap: { width: 200, minHeight: 140, overflow: "hidden", flexShrink: 0, position: "relative" },
  atrListBody: {
    flex: 1,
    padding: "14px 14px 14px 0",
    display: "flex",
    flexDirection: "column",
    gap: 4,
    justifyContent: "center",
  },
  atrListRight: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "flex-end",
    justifyContent: "space-between",
    padding: "14px 18px 14px 0",
    flexShrink: 0,
  },
  atrSaveList: {
    background: "transparent",
    border: "1px solid var(--atr-outline)",
    borderRadius: 8,
    width: 32,
    height: 32,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  atrPriceList: { fontSize: 14, fontWeight: 700, color: "var(--atr-purple)", whiteSpace: "nowrap" },
  atrCtaList: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 700,
    color: "var(--atr-text)",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  atrCtaPesan: {
    background: "var(--atr-purple)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 14px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },

  /* ─── DESA GRID ─── */
  desaGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16 },
  desaCard: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    transition: "transform .2s, box-shadow .2s",
    display: "flex",
    flexDirection: "column",
  },
  desaStatus: {
    position: "absolute",
    top: 10,
    left: 10,
    fontSize: 10,
    fontWeight: 700,
    padding: "3px 10px",
    borderRadius: 999,
  },
  desaTagRow: { display: "flex", gap: 4, flexWrap: "wrap", padding: "0 14px 10px" },
  desaTag: {
    fontSize: 10,
    fontWeight: 600,
    color: "var(--atr-purple)",
    background: "#EDE9FF",
    padding: "2px 8px",
    borderRadius: 999,
  },
  desaHighlight: {
    background: "rgba(81,176,84,0.08)",
    border: "1px solid rgba(81,176,84,0.2)",
    color: "var(--atr-text)",
    fontSize: 12,
    padding: "8px 12px",
    borderRadius: 8,
    marginTop: 4,
  },

  /* ─── ITINERARY ─── */
  itinDestGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 16 },
  itinCard: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    transition: "transform .2s, box-shadow .2s",
    display: "flex",
    flexDirection: "column",
  },
  itinDaysBadge: {
    position: "absolute",
    top: 12,
    left: 12,
    background: "#2A9D8F",
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    padding: "5px 10px",
    borderRadius: 6,
    letterSpacing: "0.04em",
  },
  itinThemeBadge: { position: "absolute", top: 12, right: 12, fontSize: 10, fontWeight: 700, padding: "5px 10px", borderRadius: 999, letterSpacing: "0.04em" },
  itinInfoRow: { display: "flex", alignItems: "center", gap: 6, fontSize: 12, color: "var(--atr-text-muted)", padding: "0 14px", marginBottom: 8 },
  itinDot: { width: 4, height: 4, borderRadius: 999, background: "var(--atr-outline)" },
  itinBudget: { marginTop: "auto", padding: "10px 14px", borderTop: "1px solid var(--atr-outline)", display: "flex", alignItems: "baseline", gap: 4 },
  itinBudgetLabel: { fontSize: 11, color: "var(--atr-text-muted)" },
  itinBudgetVal: { fontSize: 16, fontWeight: 700, color: "var(--atr-purple)" },
  itinBudgetUnit: { fontSize: 11, color: "var(--atr-text-muted)" },
  itinFooter: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 14px", borderTop: "1px solid var(--atr-outline)", gap: 8 },
  itinCreator: { display: "flex", alignItems: "center", gap: 8 },
  itinCreatorAv: { width: 28, height: 28, borderRadius: 999, objectFit: "cover" },
  itinCreatorName: { fontSize: 12, fontWeight: 700, color: "var(--atr-text)" },
  itinCreatorRole: { fontSize: 10, color: "var(--atr-text-muted)" },
  itinRatingBlock: { display: "flex", alignItems: "center", gap: 4, fontSize: 12, color: "var(--atr-yellow)", fontWeight: 700 },
  itinSaves: { fontSize: 11, color: "var(--atr-text-muted)", marginLeft: 2 },

  /* ─── GUIDE ─── */
  guideGrid: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: 16 },
  guideCard: { background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 12, overflow: "hidden", display: "flex", flexDirection: "column" },
  guideImgWrap: { position: "relative", aspectRatio: "4 / 3" },
  guideVerified: { position: "absolute", top: 10, right: 10, background: "var(--atr-purple)", color: "#fff", fontSize: 10, fontWeight: 700, padding: "4px 9px", borderRadius: 999, display: "inline-flex", alignItems: "center", gap: 4, letterSpacing: "0.02em" },
  guideBody: { padding: 14, display: "flex", flexDirection: "column", gap: 6, flex: 1 },
  guideName: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)" },
  guideSpecRow: { display: "flex", gap: 4, flexWrap: "wrap" },
  guideSpec: { fontSize: 10, fontWeight: 600, color: "var(--atr-purple)", background: "#EDE9FF", padding: "2px 8px", borderRadius: 999 },
  guideLangRow: { display: "flex", gap: 6, fontSize: 11, color: "var(--atr-text-muted)", flexWrap: "wrap" },
  guideLang: { display: "inline-flex", alignItems: "center", gap: 4 },
  guideMeta: { display: "flex", alignItems: "center", gap: 10, fontSize: 12, color: "var(--atr-text-muted)", marginTop: "auto", paddingTop: 6 },
  guideBio: { fontSize: 12, color: "var(--atr-text-muted)", lineHeight: 1.5, display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden" },
  guidePriceRow: { padding: "10px 14px", borderTop: "1px solid var(--atr-outline)", display: "flex", alignItems: "center", justifyContent: "space-between" },
  guidePrice: { fontSize: 16, fontWeight: 700, color: "var(--atr-purple)" },
  guideCerts: { display: "flex", gap: 4, padding: "0 14px 10px", flexWrap: "wrap" },
  guideCert: { fontSize: 10, color: "var(--atr-arti)", background: "#EEF7EE", padding: "2px 8px", borderRadius: 999, fontWeight: 600 },
  guideCtas: { display: "flex", gap: 8, padding: "0 14px 14px" },
  guideCtaSec: { flex: 1, background: "#fff", border: "1px solid var(--atr-purple)", color: "var(--atr-purple)", borderRadius: 8, padding: "10px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)", textDecoration: "none", textAlign: "center" },
  guideCtaPri: { flex: 1, background: "var(--atr-purple)", color: "#fff", border: "none", borderRadius: 8, padding: "10px", fontSize: 12, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)", textDecoration: "none", textAlign: "center" },

  /* ─── FILTER BAR ─── */
  tabContent: { paddingBottom: 60 },
  filterBar: { background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 14, padding: 16, marginBottom: 20, display: "flex", flexDirection: "column", gap: 14 },
  filterTopRow: { display: "flex", gap: 10, alignItems: "center" },
  filterSearch: { flex: 1, display: "flex", alignItems: "center", gap: 8, background: "var(--atr-bg-soft)", border: "1px solid var(--atr-outline)", borderRadius: 10, padding: "10px 14px" },
  filterSearchInput: { border: "none", outline: "none", background: "transparent", fontSize: 13, flex: 1, fontFamily: "var(--atr-font-sans)" },
  filterSort: { background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 10, padding: "10px 14px", fontSize: 13, fontWeight: 600, color: "var(--atr-text)", cursor: "pointer", fontFamily: "var(--atr-font-sans)" },
  viewToggle: { display: "flex", background: "var(--atr-bg-soft)", border: "1px solid var(--atr-outline)", borderRadius: 10, padding: 3 },
  viewBtn: { background: "transparent", border: "none", padding: "8px 12px", color: "var(--atr-text-muted)", cursor: "pointer", borderRadius: 8, fontFamily: "var(--atr-font-sans)" },
  viewBtnOn: { background: "#fff", color: "var(--atr-text)", boxShadow: "0 1px 3px rgba(0,0,0,0.08)" },
  fgroup: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  fgroupLabel: { fontSize: 11, fontWeight: 700, color: "var(--atr-text-muted)", textTransform: "uppercase", letterSpacing: "0.06em", minWidth: 110 },
  fgroupRow: { display: "flex", gap: 6, flexWrap: "wrap", flex: 1 },
  fgroupDivider: { width: 1, height: 18, background: "var(--atr-outline)", margin: "0 4px" },
  fchip: { background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 999, padding: "6px 12px", fontSize: 12, fontWeight: 600, color: "var(--atr-text)", cursor: "pointer", fontFamily: "var(--atr-font-sans)", display: "inline-flex", alignItems: "center", gap: 5 },
  fchipOn: { background: "var(--atr-purple)", color: "#fff", border: "1px solid var(--atr-purple)" },
  resultMeta: { marginBottom: 14 },
  resultText: { fontSize: 13, color: "var(--atr-text-muted)" },

  /* ─── SHARED ─── */
  statusDot: { width: 6, height: 6, borderRadius: 999, display: "inline-block" },
};

export default cs;
