/* Destination Hub styles — extracted from region-styles.jsx */
const rg = {
  header: {
    background: 'linear-gradient(180deg, #F6F4FF 0%, #FFFFFF 100%)',
    borderBottom: '1px solid var(--atr-outline)',
  },
  headerInner: { maxWidth: 1376, margin: '0 auto', padding: '32px 32px 28px' },
  h1: { fontSize: 38, fontWeight: 700, letterSpacing: '-0.02em', color: 'var(--atr-text)', marginTop: 12 },
  subtitle: { fontSize: 15, color: 'var(--atr-text-muted)', marginTop: 4 },
  provMiniHero: {
    marginTop: 20,
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 12,
    padding: '16px 20px',
    fontSize: 13,
    color: 'var(--atr-text)',
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    lineHeight: 1.5,
  },
  provHeroIcon: { fontSize: 24 },

  /* Filter bar */
  filterStick: {
    position: 'sticky',
    top: 71,
    zIndex: 30,
    background: '#fff',
    borderBottom: '1px solid var(--atr-outline)',
    boxShadow: '0 1px 0 var(--atr-outline)',
  },
  filterInner: {
    maxWidth: 1376,
    margin: '0 auto',
    padding: '14px 32px',
    display: 'flex',
    gap: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  filterSearchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 10,
    padding: '8px 14px',
    minWidth: 240,
  },
  filterSearch: { border: 'none', outline: 'none', background: 'transparent', fontSize: 13, fontFamily: 'var(--atr-font-sans)', flex: 1 },
  filterBtn: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--atr-text)',
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
  },
  filterCount: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'var(--atr-purple)',
    color: '#fff',
    fontSize: 10,
    fontWeight: 700,
    borderRadius: 999,
    minWidth: 18,
    height: 18,
    padding: '0 6px',
    marginLeft: 4,
  },
  provDropdown: {
    position: 'absolute',
    top: 'calc(100% + 6px)',
    left: 0,
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 12,
    boxShadow: '0 12px 32px rgba(31,27,51,0.12)',
    padding: 8,
    minWidth: 320,
    zIndex: 50,
  },
  provDropdownSearch: {
    width: '100%',
    border: '1px solid var(--atr-outline)',
    borderRadius: 8,
    padding: '8px 12px',
    fontSize: 13,
    fontFamily: 'var(--atr-font-sans)',
    outline: 'none',
    marginBottom: 6,
  },
  provDropdownList: { maxHeight: 280, overflowY: 'auto' },
  provDropdownItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    background: 'transparent',
    border: 'none',
    padding: '8px 10px',
    fontSize: 13,
    color: 'var(--atr-text)',
    cursor: 'pointer',
    borderRadius: 6,
    textAlign: 'left',
    fontFamily: 'var(--atr-font-sans)',
  },
  provDropdownIsland: { marginLeft: 'auto', fontSize: 10, color: 'var(--atr-text-muted)', background: 'var(--atr-bg-soft)', padding: '2px 8px', borderRadius: 999 },
  checkbox: { width: 16, height: 16, borderRadius: 4, border: '1.5px solid var(--atr-outline)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  checkboxOn: { background: 'var(--atr-purple)', border: '1.5px solid var(--atr-purple)' },

  islandStrip: { display: 'flex', gap: 4, flexWrap: 'wrap' },
  islandStripChip: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 999,
    padding: '8px 14px',
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--atr-text-muted)',
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },
  islandStripChipOn: { background: 'var(--atr-purple)', color: '#fff', border: '1px solid var(--atr-purple)' },

  availRow: { display: 'flex', gap: 14 },
  availLabel: { display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 13, color: 'var(--atr-text)', cursor: 'pointer', fontFamily: 'var(--atr-font-sans)' },
  availInput: { display: 'none' },
  availCheck: { width: 16, height: 16, borderRadius: 4, border: '1.5px solid var(--atr-outline)', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' },
  availCheckOn: { background: 'var(--atr-purple)', border: '1.5px solid var(--atr-purple)' },

  sortSelect: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 10,
    padding: '10px 14px',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--atr-text)',
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
    marginLeft: 'auto',
  },
  resetBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--atr-purple)',
    fontSize: 12,
    fontWeight: 700,
    textDecoration: 'underline',
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },

  /* Active chips row */
  activeChipsRow: {
    maxWidth: 1376,
    margin: '0 auto',
    padding: '0 32px 14px',
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  activeLabel: { fontSize: 11, fontWeight: 700, color: 'var(--atr-text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em' },
  activeChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    background: '#EDE9FF',
    color: 'var(--atr-purple)',
    fontSize: 12,
    fontWeight: 600,
    padding: '4px 10px',
    borderRadius: 999,
  },
  activeChipX: { background: 'transparent', border: 'none', color: 'var(--atr-purple)', cursor: 'pointer', padding: 0, fontSize: 16, lineHeight: 1, fontFamily: 'var(--atr-font-sans)' },

  /* Grid */
  gridSection: { maxWidth: 1376, margin: '0 auto', padding: '24px 32px 0' },
  resultRow: { marginBottom: 20 },
  resultText: { fontSize: 14, color: 'var(--atr-text-muted)' },
  destGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 20 },
  destCard: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 14,
    overflow: 'hidden',
    textDecoration: 'none',
    color: 'inherit',
    transition: 'transform .2s, box-shadow .2s',
    display: 'flex',
    flexDirection: 'column',
  },
  destCardHover: { transform: 'translateY(-3px)', boxShadow: '0 12px 28px rgba(31,27,51,0.1)' },
  destImgWrap: { position: 'relative', aspectRatio: '16 / 9', overflow: 'hidden' },
  destImg: { width: '100%', height: '100%', objectFit: 'cover', transition: 'transform .4s' },
  destTypeBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    background: 'rgba(255,255,255,0.95)',
    color: 'var(--atr-text)',
    fontSize: 10,
    fontWeight: 700,
    padding: '4px 9px',
    borderRadius: 999,
    letterSpacing: '0.04em',
  },
  destMarketBadge: {
    position: 'absolute',
    top: 12,
    right: 12,
    background: 'var(--atr-yellow)',
    color: '#3D2900',
    fontSize: 11,
    fontWeight: 700,
    padding: '4px 10px',
    borderRadius: 999,
    boxShadow: '0 2px 6px rgba(0,0,0,0.15)',
  },
  destHoverOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(31,27,51,0.1) 0%, rgba(112,104,213,0.85) 100%)',
    display: 'flex',
    alignItems: 'flex-end',
    padding: 16,
  },
  destHoverCTA: {
    background: '#fff',
    color: 'var(--atr-purple)',
    padding: '10px 16px',
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 700,
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
  },
  destBody: { padding: 16, display: 'flex', flexDirection: 'column', gap: 12, flex: 1 },
  destHeaderRow: { display: 'flex', justifyContent: 'space-between', gap: 12 },
  destName: { fontSize: 18, fontWeight: 700, letterSpacing: '-0.01em', color: 'var(--atr-text)', lineHeight: 1.2 },
  destProvRow: { display: 'flex', alignItems: 'center', gap: 6, marginTop: 4, flexWrap: 'wrap' },
  destProv: { fontSize: 12, color: 'var(--atr-text-muted)' },
  destIslandPill: { fontSize: 10, fontWeight: 700, color: 'var(--atr-purple)', background: '#EDE9FF', padding: '2px 8px', borderRadius: 999 },
  destRating: { display: 'inline-flex', alignItems: 'center', gap: 4, fontSize: 13, color: 'var(--atr-text)' },
  destStar: { color: 'var(--atr-yellow)' },

  destStatsBar: {
    display: 'flex',
    alignItems: 'center',
    background: 'var(--atr-bg-soft)',
    border: '1px solid var(--atr-outline)',
    borderRadius: 8,
    padding: '8px 6px',
    gap: 0,
  },
  destStat: { flex: 1, textAlign: 'center', fontSize: 10, color: 'var(--atr-text-muted)' },
  destStatDiv: { width: 1, height: 24, background: 'var(--atr-outline)' },

  destTagRow: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  destTag: { fontSize: 10, fontWeight: 600, color: 'var(--atr-text-muted)', background: 'var(--atr-bg-soft)', border: '1px solid var(--atr-outline)', padding: '3px 8px', borderRadius: 999 },

  loadMoreWrap: { display: 'flex', justifyContent: 'center', marginTop: 40 },
  loadMoreBtn: {
    background: '#fff',
    border: '1.5px solid var(--atr-purple)',
    color: 'var(--atr-purple)',
    borderRadius: 10,
    padding: '12px 28px',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },

  empty: { textAlign: 'center', padding: '80px 20px' },
  emptyIcon: { fontSize: 64 },
  emptyTitle: { fontSize: 18, fontWeight: 700, color: 'var(--atr-text)', marginTop: 12 },
  emptySub: { fontSize: 14, color: 'var(--atr-text-muted)', marginTop: 4 },
  emptyBtn: { marginTop: 20, background: 'var(--atr-purple)', color: '#fff', border: 'none', borderRadius: 10, padding: '12px 24px', fontSize: 14, fontWeight: 700, cursor: 'pointer', fontFamily: 'var(--atr-font-sans)' },
};

export default rg;
