/* Attraction Detail styles — from detail-shared.jsx + attraction-detail.jsx */
const ds = {
  pageWrap: { background: "var(--atr-bg-soft)", paddingBottom: 24 },
  containerWide: { maxWidth: 1376, margin: "0 auto", padding: "0 32px" },
  crumbBar: { maxWidth: 1376, margin: "0 auto", padding: "18px 32px 6px" },

  twoCol: {
    maxWidth: 1376,
    margin: "0 auto",
    padding: "24px 32px 24px",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 380px",
    gap: 28,
    alignItems: "flex-start",
  },
  mainCol: { display: "flex", flexDirection: "column", gap: 20, minWidth: 0 },
  sideCol: {
    position: "sticky",
    top: 96,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },

  section: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    padding: 24,
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 18,
    flexWrap: "wrap",
    gap: 12,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 700,
    letterSpacing: "-0.01em",
    color: "var(--atr-text)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    margin: 0,
  },
  sectionSub: { fontSize: 13, color: "var(--atr-text-muted)", marginTop: 4 },
  sectionLink: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--atr-purple)",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },

  longText: { fontSize: 14.5, lineHeight: 1.7, color: "var(--atr-text)" },
  longTextClamped: {
    fontSize: 14.5,
    lineHeight: 1.7,
    color: "var(--atr-text)",
    display: "-webkit-box",
    WebkitLineClamp: 4,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  readMoreBtn: {
    background: "transparent",
    border: "none",
    color: "var(--atr-purple)",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    padding: 0,
    marginTop: 8,
    fontFamily: "var(--atr-font-sans)",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },

  galleryRow: {
    display: "grid",
    gridTemplateColumns: "1.7fr 1fr",
    gap: 8,
    height: 460,
    borderRadius: 16,
    overflow: "hidden",
  },
  galleryMain: { position: "relative", overflow: "hidden", cursor: "zoom-in" },
  galleryMainImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  galleryThumbCol: { display: "grid", gridTemplateRows: "1fr 1fr", gap: 8 },
  galleryThumbRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 },
  galleryThumb: { position: "relative", overflow: "hidden", cursor: "zoom-in" },
  galleryThumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  galleryMore: {
    position: "absolute",
    inset: 0,
    background: "rgba(31,27,51,0.5)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    gap: 4,
    cursor: "pointer",
  },
  galleryMoreNum: { fontSize: 26, fontWeight: 700 },
  galleryMoreLabel: {
    fontSize: 12,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    fontWeight: 600,
  },

  hdrBadgeRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 10,
  },
  catBadge: {
    fontSize: 11,
    fontWeight: 700,
    padding: "5px 11px",
    borderRadius: 999,
    letterSpacing: "0.04em",
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
  },
  certBadge: {
    fontSize: 10,
    fontWeight: 700,
    padding: "4px 9px",
    borderRadius: 6,
    letterSpacing: "0.06em",
    border: "1px solid",
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
  },
  hdrTitle: {
    fontSize: 36,
    fontWeight: 700,
    letterSpacing: "-0.02em",
    color: "var(--atr-text)",
    lineHeight: 1.1,
    margin: "4px 0 0",
  },
  hdrMetaRow: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    flexWrap: "wrap",
    marginTop: 14,
    fontSize: 13,
    color: "var(--atr-text)",
  },
  hdrMetaItem: { display: "inline-flex", alignItems: "center", gap: 6 },
  hdrMetaLink: {
    color: "var(--atr-purple)",
    textDecoration: "none",
    fontWeight: 600,
  },
  hdrTagRow: { display: "flex", gap: 6, flexWrap: "wrap", marginTop: 14 },
  hdrTag: {
    fontSize: 11.5,
    fontWeight: 600,
    color: "var(--atr-text)",
    background: "var(--atr-bg-soft)",
    border: "1px solid var(--atr-outline)",
    padding: "5px 10px",
    borderRadius: 999,
  },
  hdrShortDesc: {
    fontSize: 15,
    lineHeight: 1.6,
    color: "var(--atr-text)",
    marginTop: 18,
    maxWidth: 720,
  },

  bookCard: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    padding: 20,
    boxShadow: "0 8px 24px rgba(31,27,51,0.06)",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  bookHead: { display: "flex", flexDirection: "column", gap: 4 },
  bookEyebrow: {
    fontSize: 11,
    fontWeight: 700,
    color: "var(--atr-text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
  },
  bookFromRow: { display: "flex", alignItems: "baseline", gap: 6 },
  bookFromVal: {
    fontSize: 26,
    fontWeight: 700,
    color: "var(--atr-purple)",
    letterSpacing: "-0.01em",
  },
  bookFromUnit: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--atr-text-muted)",
  },

  priceTable: {
    background: "var(--atr-bg-soft)",
    borderRadius: 10,
    padding: "12px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  priceRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: 13,
  },
  priceLabel: {
    color: "var(--atr-text)",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  priceVal: { fontWeight: 700, color: "var(--atr-text)" },

  opRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "4px 0",
    fontSize: 13,
    color: "var(--atr-text)",
    borderBottom: "1px dashed var(--atr-outline)",
  },
  opDay: { color: "var(--atr-text-muted)" },
  opHours: { fontWeight: 600 },

  statusChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "6px 12px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 700,
    width: "fit-content",
  },
  statusOpen: {
    background: "rgba(81,176,84,0.12)",
    color: "#1F7A21",
    border: "1px solid rgba(81,176,84,0.3)",
  },
  statusClosed: {
    background: "rgba(244,98,99,0.1)",
    color: "#8C2A2B",
    border: "1px solid rgba(244,98,99,0.3)",
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    display: "inline-block",
  },

  primaryCta: {
    background: "var(--atr-purple)",
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "13px 16px",
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "0 6px 16px rgba(112,104,213,0.3)",
    fontFamily: "var(--atr-font-sans)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
  },
  secondaryCta: {
    background: "#fff",
    color: "var(--atr-purple)",
    border: "1.5px solid var(--atr-purple)",
    borderRadius: 10,
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
  },
  iconRow: { display: "flex", gap: 8 },
  iconBtnGhost: {
    flex: 1,
    background: "var(--atr-bg-soft)",
    color: "var(--atr-text)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 10,
    padding: "10px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  iconBtnOn: {
    background: "#EDE9FF",
    color: "var(--atr-purple)",
    border: "1px solid var(--atr-purple-light)",
  },

  facGrid: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 10 },
  facItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "var(--atr-bg-soft)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 10,
    padding: "10px 12px",
  },
  facItemOff: {
    background: "#fff",
    color: "var(--atr-text-muted)",
    opacity: 0.55,
  },
  facIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    background: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    flexShrink: 0,
  },
  facLabel: { fontSize: 13, fontWeight: 600 },
  facStrike: { textDecoration: "line-through" },

  mapBox: {
    borderRadius: 12,
    overflow: "hidden",
    border: "1px solid var(--atr-outline)",
    aspectRatio: "16 / 9",
    background: "var(--atr-bg-soft)",
    position: "relative",
  },
  mapImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  mapPin: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -100%)",
    fontSize: 32,
    filter: "drop-shadow(0 4px 6px rgba(0,0,0,0.3))",
  },
  mapCoordChip: {
    position: "absolute",
    bottom: 12,
    left: 12,
    background: "rgba(255,255,255,0.95)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 8,
    padding: "6px 10px",
    fontSize: 11,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    color: "var(--atr-text)",
  },
  mapDirBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    background: "var(--atr-purple)",
    color: "#fff",
    border: "none",
    borderRadius: 8,
    padding: "8px 12px",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
  },
  accessTip: {
    background: "var(--atr-bg-soft)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 10,
    padding: 14,
    marginTop: 12,
    fontSize: 13,
    lineHeight: 1.6,
    color: "var(--atr-text)",
  },

  tipsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 12 },
  tipBox: {
    borderRadius: 12,
    padding: 16,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  tipBest: { background: "#EDE9FF", border: "1px solid #D8D0FF" },
  tipBring: {
    background: "rgba(81,176,84,0.08)",
    border: "1px solid rgba(81,176,84,0.2)",
  },
  tipWarn: { background: "#FFFBEE", border: "1px solid #FFE9A8" },
  tipIcon: { fontSize: 22 },
  tipTitle: { fontSize: 13, fontWeight: 700, color: "var(--atr-text)" },
  tipBody: {
    fontSize: 13,
    lineHeight: 1.5,
    color: "var(--atr-text)",
    margin: 0,
  },
  tipList: {
    fontSize: 13,
    lineHeight: 1.6,
    color: "var(--atr-text)",
    margin: 0,
    paddingLeft: 18,
  },

  hScroll: {
    display: "grid",
    gridAutoFlow: "column",
    gridAutoColumns: "minmax(230px, 240px)",
    gap: 14,
    overflowX: "auto",
    paddingBottom: 8,
    scrollSnapType: "x mandatory",
  },
  miniCard: {
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 12,
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    display: "flex",
    flexDirection: "column",
    cursor: "pointer",
    scrollSnapAlign: "start",
  },
  miniImg: {
    width: "100%",
    aspectRatio: "4 / 3",
    objectFit: "cover",
    display: "block",
  },
  miniBody: { padding: 12, display: "flex", flexDirection: "column", gap: 5 },
  miniCat: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.04em",
    color: "var(--atr-purple)",
    textTransform: "uppercase",
  },
  miniName: {
    fontSize: 14,
    fontWeight: 700,
    color: "var(--atr-text)",
    lineHeight: 1.3,
  },
  miniMeta: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: 4,
    fontSize: 12,
  },
  miniRating: { color: "var(--atr-text)" },
  miniPrice: { color: "var(--atr-purple)", fontWeight: 700 },

  reviewTop: {
    display: "grid",
    gridTemplateColumns: "1fr 1.8fr",
    gap: 28,
    alignItems: "flex-start",
  },
  ratingSummary: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    background: "linear-gradient(180deg, #F6F4FF 0%, #fff 100%)",
    border: "1px solid #EDE9FF",
    borderRadius: 12,
    padding: "20px 16px",
  },
  ratingBig: {
    fontSize: 48,
    fontWeight: 700,
    color: "var(--atr-purple)",
    lineHeight: 1,
    letterSpacing: "-0.02em",
  },
  ratingStars: {
    fontSize: 16,
    letterSpacing: "0.1em",
    color: "var(--atr-yellow)",
  },
  ratingCount: { fontSize: 12, color: "var(--atr-text-muted)" },
  breakdownCol: { display: "flex", flexDirection: "column", gap: 8 },
  breakdownRow: {
    display: "grid",
    gridTemplateColumns: "60px 1fr 60px",
    gap: 12,
    alignItems: "center",
    fontSize: 13,
  },
  breakdownStar: { color: "var(--atr-text-muted)" },
  breakdownTrack: {
    background: "var(--atr-bg-soft)",
    height: 8,
    borderRadius: 999,
    overflow: "hidden",
  },
  breakdownFill: {
    height: "100%",
    background: "var(--atr-yellow)",
    borderRadius: 999,
  },
  breakdownPct: { textAlign: "right", color: "var(--atr-text-muted)" },

  reviewList: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    marginTop: 24,
  },
  reviewCard: {
    display: "grid",
    gridTemplateColumns: "44px 1fr",
    gap: 14,
    paddingBottom: 16,
    borderBottom: "1px solid var(--atr-outline)",
  },
  reviewAv: { width: 44, height: 44, borderRadius: 999 },
  reviewHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 10,
    flexWrap: "wrap",
  },
  reviewName: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)" },
  reviewDate: { fontSize: 12, color: "var(--atr-text-muted)" },
  reviewMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginTop: 3,
    fontSize: 12,
    color: "var(--atr-text-muted)",
  },
  reviewStarRow: {
    color: "var(--atr-yellow)",
    fontSize: 13,
    letterSpacing: "0.05em",
  },
  reviewVerified: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    fontSize: 11,
    color: "var(--atr-arti)",
    background: "rgba(81,176,84,0.1)",
    padding: "2px 7px",
    borderRadius: 6,
    fontWeight: 700,
  },
  reviewText: {
    fontSize: 14,
    lineHeight: 1.55,
    color: "var(--atr-text)",
    margin: "10px 0 0",
  },
  reviewPhotos: { display: "flex", gap: 6, marginTop: 10 },
  reviewPhoto: { width: 72, height: 72, borderRadius: 8, objectFit: "cover" },
  loadMoreBtn: {
    marginTop: 20,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 10,
    padding: "12px 18px",
    fontSize: 13,
    fontWeight: 700,
    color: "var(--atr-text)",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    display: "block",
    margin: "20px auto 0",
  },
};

/* Review Gallery styles */
const rgS = {
  entryBtn: {
    background: "var(--atr-bg-soft)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: "8px 14px",
    fontSize: 13,
    fontWeight: 700,
    color: "var(--atr-text)",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  writeBtn: {
    background: "var(--atr-purple)",
    border: "none",
    borderRadius: 999,
    padding: "9px 16px",
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    marginLeft: 8,
  },
  scrim: {
    position: "fixed",
    inset: 0,
    background: "rgba(31,27,51,0.55)",
    backdropFilter: "blur(3px)",
    zIndex: 9000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modal: {
    background: "#fff",
    borderRadius: 20,
    width: "min(680px,100%)",
    maxHeight: "calc(100vh - 48px)",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 30px 70px rgba(31,27,51,0.4)",
    fontFamily: "var(--atr-font-sans)",
  },
  modalHead: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "20px 24px 16px",
    borderBottom: "1px solid var(--atr-outline)",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: "var(--atr-text)",
    letterSpacing: "-0.01em",
  },
  x: {
    width: 34,
    height: 34,
    borderRadius: 999,
    border: "none",
    background: "var(--atr-bg-soft)",
    cursor: "pointer",
    fontSize: 15,
    color: "var(--atr-text-muted)",
  },
  modalBody: { padding: "20px 24px", overflowY: "auto" },
  modalFoot: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 10,
    padding: "16px 24px",
    borderTop: "1px solid var(--atr-outline)",
  },
  label: {
    fontSize: 13,
    fontWeight: 700,
    color: "var(--atr-text)",
    marginBottom: 8,
  },
  textarea: {
    width: "100%",
    minHeight: 90,
    borderRadius: 12,
    border: "1.5px solid var(--atr-outline)",
    padding: 12,
    fontSize: 14,
    fontFamily: "var(--atr-font-sans)",
    outline: "none",
    resize: "vertical",
    marginBottom: 16,
    boxSizing: "border-box",
  },
  photoRow: { display: "flex", gap: 10, flexWrap: "wrap" },
  photoThumb: {
    position: "relative",
    width: 84,
    height: 84,
    borderRadius: 12,
    overflow: "hidden",
  },
  photoThumbImg: { width: "100%", height: "100%", objectFit: "cover" },
  photoRm: {
    position: "absolute",
    top: 4,
    right: 4,
    width: 22,
    height: 22,
    borderRadius: 999,
    border: "none",
    background: "rgba(0,0,0,0.6)",
    color: "#fff",
    cursor: "pointer",
    fontSize: 11,
  },
  uploadTile: {
    width: 84,
    height: 84,
    borderRadius: 12,
    border: "1.5px dashed var(--atr-purple-light)",
    background: "var(--atr-purple-50)",
    color: "var(--atr-purple)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    fontWeight: 700,
  },
  tabs: { display: "flex", gap: 8, padding: "12px 24px 0" },
  tab: {
    background: "none",
    border: "none",
    borderBottom: "2.5px solid transparent",
    padding: "8px 4px",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--atr-text-muted)",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  tabOn: { color: "var(--atr-purple)", borderBottomColor: "var(--atr-purple)" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(120px,1fr))",
    gap: 8,
  },
  gridCell: {
    aspectRatio: "1/1",
    borderRadius: 10,
    overflow: "hidden",
    cursor: "zoom-in",
  },
  gridImg: { width: "100%", height: "100%", objectFit: "cover" },
  empty: { textAlign: "center", padding: "40px 20px" },
  ghostBtn: {
    background: "none",
    border: "1px solid var(--atr-outline)",
    borderRadius: 10,
    padding: "10px 18px",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--atr-text)",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  primaryBtn: {
    background: "var(--atr-purple)",
    border: "none",
    borderRadius: 10,
    padding: "10px 20px",
    fontSize: 14,
    fontWeight: 700,
    color: "#fff",
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  lightbox: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.85)",
    zIndex: 9100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 30,
    cursor: "zoom-out",
  },
  lightboxImg: { maxWidth: "100%", maxHeight: "100%", borderRadius: 12 },
};

/* Attraction detail specific styles */
const adStyles = {
  itinList: { display: "grid", gridTemplateColumns: "1fr", gap: 12 },
  itinRow: {
    display: "grid",
    gridTemplateColumns: "180px 1fr auto",
    gap: 16,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 12,
    overflow: "hidden",
    textDecoration: "none",
    color: "inherit",
    cursor: "pointer",
  },
  itinImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    aspectRatio: "4 / 3",
  },
  itinBody: {
    padding: "14px 0",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    justifyContent: "center",
  },
  itinBadgeRow: { display: "flex", gap: 6, alignItems: "center" },
  itinDayBadge: {
    background: "#2A9D8F",
    color: "#fff",
    fontSize: 10,
    fontWeight: 700,
    padding: "4px 9px",
    borderRadius: 6,
    letterSpacing: "0.04em",
  },
  itinThemeBadge: {
    fontSize: 10,
    fontWeight: 700,
    padding: "4px 9px",
    borderRadius: 999,
    letterSpacing: "0.04em",
  },
  itinTitle: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)" },
  itinMetaRow: {
    display: "flex",
    gap: 10,
    fontSize: 12,
    color: "var(--atr-text-muted)",
  },
  itinRight: {
    padding: 16,
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 6,
    borderLeft: "1px dashed var(--atr-outline)",
  },
  itinPrice: { fontSize: 16, fontWeight: 700, color: "var(--atr-purple)" },
  itinPriceLabel: {
    fontSize: 10,
    color: "var(--atr-text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  itinCreator: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    color: "var(--atr-text-muted)",
  },
  itinCreatorAv: { width: 22, height: 22, borderRadius: 999 },
};

export { ds, rgS, adStyles };
