/* Explore Hub styles — extracted from explore-styles.jsx */
const ex = {
  /* HERO */
  hero: {
    position: 'relative',
    minHeight: 580,
    overflow: 'hidden',
    background: '#1F1B33',
  },
  heroBg: {
    position: 'absolute',
    inset: 0,
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    transition: 'opacity 1.2s ease',
  },
  heroOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(180deg, rgba(31,27,51,0.35) 0%, rgba(31,27,51,0.55) 60%, rgba(31,27,51,0.85) 100%)',
  },
  heroDots: {
    position: 'absolute',
    top: 24,
    right: 32,
    display: 'flex',
    gap: 6,
    zIndex: 3,
  },
  heroDot: {
    width: 28,
    height: 4,
    background: 'rgba(255,255,255,0.35)',
    border: 'none',
    borderRadius: 999,
    cursor: 'pointer',
    transition: 'background .25s',
  },
  heroDotActive: { background: '#fff' },
  heroContent: {
    position: 'relative',
    maxWidth: 1100,
    margin: '0 auto',
    padding: '112px 32px 80px',
    color: '#fff',
    textAlign: 'center',
    zIndex: 2,
  },
  heroTitle: {
    fontSize: 64,
    fontWeight: 700,
    letterSpacing: '-0.02em',
    lineHeight: 1.05,
    textShadow: '0 2px 24px rgba(0,0,0,0.3)',
  },
  heroSub: {
    fontSize: 18,
    color: 'rgba(255,255,255,0.92)',
    marginTop: 16,
    maxWidth: 640,
    margin: '16px auto 0',
    textShadow: '0 1px 8px rgba(0,0,0,0.3)',
  },
  searchWrap: {
    position: 'relative',
    maxWidth: 720,
    margin: '32px auto 0',
  },
  searchInner: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    background: '#fff',
    borderRadius: 14,
    padding: '10px 12px 10px 20px',
    boxShadow: '0 20px 40px rgba(0,0,0,0.25)',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    background: 'transparent',
    flex: 1,
    fontSize: 15,
    color: 'var(--atr-text)',
    fontFamily: 'var(--atr-font-sans)',
    padding: '10px 4px',
  },
  searchBtn: {
    background: 'var(--atr-purple)',
    color: '#fff',
    border: 'none',
    borderRadius: 10,
    padding: '12px 28px',
    fontSize: 14,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },
  autocomplete: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    left: 0,
    right: 0,
    background: '#fff',
    borderRadius: 14,
    boxShadow: '0 20px 40px rgba(0,0,0,0.2)',
    padding: 8,
    textAlign: 'left',
    maxHeight: 360,
    overflowY: 'auto',
    zIndex: 5,
  },
  acGroup: {
    fontSize: 10,
    fontWeight: 700,
    color: 'var(--atr-purple)',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    padding: '8px 12px 4px',
  },
  acItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    fontSize: 14,
    color: 'var(--atr-text)',
    cursor: 'pointer',
    borderRadius: 8,
    textDecoration: 'none',
  },
  heroChips: {
    display: 'flex',
    gap: 8,
    justifyContent: 'center',
    marginTop: 24,
    flexWrap: 'wrap',
  },
  heroChip: {
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.3)',
    color: '#fff',
    padding: '8px 16px',
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 600,
    backdropFilter: 'blur(8px)',
    cursor: 'pointer',
    textDecoration: 'none',
    transition: 'all .2s',
  },

  /* STATS */
  stats: {
    background: 'linear-gradient(135deg, #7068D5 0%, #524BAA 100%)',
    color: '#fff',
    padding: '32px 32px',
  },
  statsInner: {
    maxWidth: 1376,
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
    gap: 24,
  },
  statCell: { textAlign: 'center', padding: '0 16px', position: 'relative' },
  statN: { fontSize: 36, fontWeight: 700, letterSpacing: '-0.01em', lineHeight: 1.1 },
  statL: { fontSize: 13, opacity: 0.85, marginTop: 4, letterSpacing: '0.02em' },

  /* COMMON SECTION */
  section: {
    maxWidth: 1376,
    margin: '0 auto',
    padding: '64px 32px 0',
  },
  secHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 24,
    flexWrap: 'wrap',
    gap: 12,
  },
  eyebrow: { fontSize: 12, fontWeight: 700, color: 'var(--atr-purple)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 6 },
  secTitle: { fontSize: 32, fontWeight: 700, letterSpacing: '-0.01em', color: 'var(--atr-text)' },
  viewAll: { color: 'var(--atr-purple)', fontSize: 14, fontWeight: 700, textDecoration: 'none' },

  /* CAROUSEL */
  carouselNav: { display: 'flex', gap: 8 },
  navBtn: {
    width: 40,
    height: 40,
    borderRadius: 999,
    border: '1px solid var(--atr-outline)',
    background: '#fff',
    fontSize: 20,
    color: 'var(--atr-text)',
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },
  navBtnDisabled: { opacity: 0.4, cursor: 'not-allowed' },
  carouselViewport: { overflow: 'hidden' },
  carouselTrack: {
    display: 'flex',
    gap: 16,
    transition: 'transform .35s ease',
  },
  featCard: {
    flex: '0 0 calc(25% - 12px)',
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 14,
    overflow: 'hidden',
    cursor: 'pointer',
    transition: 'transform .2s, box-shadow .2s',
  },
  featImgWrap: { position: 'relative', aspectRatio: '16 / 11' },
  featImg: { width: '100%', height: '100%', objectFit: 'cover' },
  featBadge: {
    position: 'absolute',
    top: 12,
    left: 12,
    color: '#fff',
    fontSize: 10,
    fontWeight: 700,
    padding: '4px 9px',
    borderRadius: 999,
    letterSpacing: '0.04em',
  },
  featBody: { padding: 14 },
  featTitle: { fontSize: 15, fontWeight: 700, lineHeight: 1.3, color: 'var(--atr-text)' },
  featFooter: { display: 'flex', justifyContent: 'space-between', marginTop: 10, fontSize: 12 },
  featLoc: { color: 'var(--atr-text-muted)' },
  featRating: { color: 'var(--atr-yellow)', fontWeight: 700 },
  carouselDots: { display: 'flex', justifyContent: 'center', gap: 6, marginTop: 18 },
  cDot: { width: 8, height: 8, borderRadius: 999, background: 'var(--atr-outline)', border: 'none', cursor: 'pointer' },
  cDotActive: { background: 'var(--atr-purple)', width: 24 },

  /* ISLAND TILES */
  islandGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gridTemplateRows: '200px 200px',
    gap: 14,
  },
  islandTile: {
    position: 'relative',
    borderRadius: 14,
    overflow: 'hidden',
    cursor: 'pointer',
    textDecoration: 'none',
    color: '#fff',
    transition: 'transform .25s',
  },
  islandTileBig: { gridRow: 'span 2' },
  islandImg: { position: 'absolute', inset: 0, width: '100%', height: '100%', objectFit: 'cover' },
  islandOverlay: { position: 'absolute', inset: 0, background: 'linear-gradient(180deg, rgba(0,0,0,0) 30%, rgba(0,0,0,0.7) 100%)' },
  islandBody: { position: 'absolute', left: 16, bottom: 14, right: 16, zIndex: 2 },
  islandName: { fontSize: 22, fontWeight: 700, letterSpacing: '-0.01em' },
  islandMeta: { fontSize: 13, opacity: 0.9, marginTop: 2 },

  /* PROVINCE GRID */
  provSortRow: { display: 'flex', gap: 4, background: 'var(--atr-bg-soft)', border: '1px solid var(--atr-outline)', borderRadius: 999, padding: 3 },
  sortToggle: {
    background: 'transparent',
    border: 'none',
    padding: '8px 16px',
    fontSize: 13,
    fontWeight: 600,
    color: 'var(--atr-text-muted)',
    borderRadius: 999,
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },
  sortToggleActive: { background: '#fff', color: 'var(--atr-text)', boxShadow: '0 1px 3px rgba(0,0,0,0.08)' },
  provFilters: { display: 'flex', gap: 12, marginBottom: 20, alignItems: 'center', flexWrap: 'wrap' },
  provSearchWrap: { display: 'flex', alignItems: 'center', gap: 8, background: '#fff', border: '1px solid var(--atr-outline)', borderRadius: 10, padding: '10px 16px', minWidth: 240 },
  provSearch: { border: 'none', outline: 'none', background: 'transparent', fontSize: 14, fontFamily: 'var(--atr-font-sans)', flex: 1 },
  islandChips: { display: 'flex', gap: 6, flexWrap: 'wrap' },
  islandChip: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    padding: '6px 14px',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--atr-text-muted)',
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },
  islandChipActive: { background: 'var(--atr-purple)', color: '#fff', border: '1px solid var(--atr-purple)' },
  provGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 },
  provCard: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 12,
    overflow: 'hidden',
    cursor: 'pointer',
    textDecoration: 'none',
    color: 'inherit',
    transition: 'transform .15s, box-shadow .15s',
  },
  provImgWrap: { position: 'relative', aspectRatio: '16 / 10' },
  provImg: { width: '100%', height: '100%', objectFit: 'cover' },
  provIslandBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    background: 'rgba(255,255,255,0.95)',
    color: 'var(--atr-purple)',
    padding: '3px 8px',
    borderRadius: 999,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.02em',
  },
  provBody: { padding: 14 },
  provName: { fontSize: 15, fontWeight: 700, color: 'var(--atr-text)' },
  provStats: { display: 'flex', gap: 4, marginTop: 6, fontSize: 11, color: 'var(--atr-text-muted)' },
  provDot: { color: 'var(--atr-outline)' },
  emptyState: { textAlign: 'center', padding: 60 },
  emptyIcon: { fontSize: 56 },
  emptyTitle: { fontSize: 16, fontWeight: 600, color: 'var(--atr-text)', marginTop: 8 },
  emptyBtn: { marginTop: 16, background: 'var(--atr-purple)', color: '#fff', border: 'none', borderRadius: 8, padding: '10px 18px', fontWeight: 700, cursor: 'pointer', fontFamily: 'var(--atr-font-sans)' },

  /* CATEGORY GRID */
  catGrid: { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 12 },
  catCard: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 12,
    padding: '20px 12px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    cursor: 'pointer',
    textDecoration: 'none',
    color: 'inherit',
    transition: 'all .2s',
  },
  catIcon: {
    width: 60,
    height: 60,
    borderRadius: 14,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 28,
  },
  catName: { fontSize: 13, fontWeight: 700, color: 'var(--atr-text)' },

  /* DESA */
  desaGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16 },
  desaCard: {
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 12,
    overflow: 'hidden',
  },
  desaImg: { width: '100%', aspectRatio: '16 / 10', objectFit: 'cover' },
  desaBody: { padding: 14 },
  desaTag: { display: 'inline-block', fontSize: 10, fontWeight: 700, color: 'var(--atr-arti)', background: 'rgba(81,176,84,0.1)', padding: '3px 8px', borderRadius: 999, letterSpacing: '0.04em' },
  desaName: { fontSize: 16, fontWeight: 700, color: 'var(--atr-text)', marginTop: 8 },
  desaMeta: { fontSize: 12, color: 'var(--atr-text-muted)', marginTop: 2 },

  /* CTA */
  ctaWrap: {
    maxWidth: 1376,
    margin: '80px auto 0',
    padding: '0 32px',
  },
  ctaInner: {
    background: 'linear-gradient(135deg, #1F1B33 0%, #2D2849 100%)',
    color: '#fff',
    borderRadius: 24,
    padding: '48px 56px',
    display: 'grid',
    gridTemplateColumns: '1.4fr 1fr',
    gap: 48,
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  ctaEyebrow: { fontSize: 12, fontWeight: 700, color: 'var(--atr-yellow)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: 8 },
  ctaTitle: { fontSize: 36, fontWeight: 700, letterSpacing: '-0.01em', lineHeight: 1.1 },
  ctaSub: { fontSize: 15, color: 'rgba(255,255,255,0.78)', marginTop: 14, lineHeight: 1.6, maxWidth: 520 },
  ctaBtn: {
    marginTop: 24,
    background: 'var(--atr-yellow)',
    color: '#1F1B33',
    border: 'none',
    borderRadius: 10,
    padding: '14px 26px',
    fontSize: 15,
    fontWeight: 700,
    cursor: 'pointer',
    fontFamily: 'var(--atr-font-sans)',
  },
  ctaIllust: { position: 'relative', height: 200 },
  ctaIllustCard: { position: 'absolute', top: 20, left: '10%', width: 80, height: 80, background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: 16, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 36, backdropFilter: 'blur(8px)', transform: 'rotate(-8deg)' },
  ctaIllustCard2: { position: 'absolute', top: 60, left: '40%', width: 80, height: 80, background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: 16, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 36, backdropFilter: 'blur(8px)', transform: 'rotate(5deg)' },
  ctaIllustCard3: { position: 'absolute', top: 100, left: '70%', width: 80, height: 80, background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: 16, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 36, backdropFilter: 'blur(8px)', transform: 'rotate(-3deg)' },
};

export default ex;
