/* Layout component styles — TopNav, Breadcrumb, and site chrome */
const layoutStyles = {
  header: {
    position: 'sticky',
    top: 0,
    zIndex: 50,
    background: '#fff',
    borderBottom: '1px solid var(--atr-outline)',
  },
  headerInner: {
    maxWidth: 1440,
    margin: '0 auto',
    padding: '14px 32px',
    display: 'grid',
    gridTemplateColumns: 'auto 1fr auto auto auto auto',
    alignItems: 'center',
    gap: 18,
  },
  logo: { display: 'flex', alignItems: 'center', textDecoration: 'none' },
  logoImg: { height: 28, width: 'auto', display: 'block' },
  searchSlot: { maxWidth: 480, width: '100%', justifySelf: 'center' },
  searchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 999,
    padding: '10px 18px',
    maxWidth: 480,
    width: '100%',
    justifySelf: 'center',
    boxShadow: '0 1px 2px rgba(0,0,0,0.03)',
  },
  searchInput: {
    border: 'none',
    outline: 'none',
    background: 'transparent',
    width: '100%',
    fontFamily: 'var(--atr-font-sans)',
    fontSize: 14,
    color: 'var(--atr-text)',
  },
  nav: { display: 'flex', gap: 22 },
  navItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    color: 'var(--atr-text)',
    textDecoration: 'none',
    fontSize: 12,
    fontWeight: 500,
    padding: '4px 6px',
    borderRadius: 8,
    transition: 'color .15s',
  },
  navItemActive: {
    color: 'var(--atr-purple)',
    fontWeight: 700,
  },
  plannerCta: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    background: 'var(--atr-purple)',
    color: '#fff',
    border: 'none',
    borderRadius: 999,
    padding: '9px 16px',
    fontSize: 13,
    fontWeight: 700,
    fontFamily: 'var(--atr-font-sans)',
    textDecoration: 'none',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(112,104,213,0.28)',
    whiteSpace: 'nowrap',
    transition: 'transform .15s, box-shadow .15s',
  },
  signInBtn: {
    background: '#fff',
    color: 'var(--atr-text)',
    border: '1px solid var(--atr-outline)',
    borderRadius: 8,
    padding: '10px 22px',
    fontFamily: 'var(--atr-font-sans)',
    fontWeight: 600,
    fontSize: 14,
    cursor: 'pointer',
  },
  drawerHead: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '18px 20px', borderBottom: '1px solid var(--atr-outline)' },
  drawerClose: { width: 38, height: 38, borderRadius: 10, border: '1px solid var(--atr-outline)', background: '#fff', color: 'var(--atr-text)', cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center' },
  drawerCta: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, margin: '16px 20px 8px', background: 'var(--atr-purple)', color: '#fff', borderRadius: 12, padding: '13px', fontSize: 14.5, fontWeight: 700, textDecoration: 'none', boxShadow: '0 8px 20px rgba(112,104,213,0.3)' },
  drawerNav: { display: 'flex', flexDirection: 'column', padding: '8px 12px', gap: 2 },
  drawerLink: { display: 'flex', alignItems: 'center', gap: 12, padding: '13px 14px', borderRadius: 11, fontSize: 15, fontWeight: 600, color: 'var(--atr-text)', textDecoration: 'none' },
  drawerMitra: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, margin: 'auto 20px 24px', background: 'rgba(112,104,213,0.1)', border: '1px solid rgba(112,104,213,0.25)', color: 'var(--atr-purple)', borderRadius: 12, padding: '13px', fontSize: 14, fontWeight: 700, textDecoration: 'none' },
  crumb: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 12.5, color: 'var(--atr-text-muted)', padding: '10px 0', maxWidth: 1376, margin: '0 auto' },
  crumbItem: { color: 'var(--atr-text-muted)', cursor: 'pointer' },
  crumbCurrent: { color: 'var(--atr-text)', fontWeight: 600 },
  crumbSep: { color: 'var(--atr-outline)', fontSize: 12 },
};

export default layoutStyles;
