export const pesanStyles = {
  /* ===== Sub-nav (Experience / Attraction / Event / Homestay / Jelajahi) ===== */
  subNav: {
    background: "#fff",
    borderBottom: "1px solid var(--atr-outline)",
    position: "sticky",
    top: 76,
    zIndex: 40,
  },
  subNavInner: {
    maxWidth: 1376,
    margin: "0 auto",
    padding: "0 32px",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  subTab: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    padding: "16px 18px",
    fontSize: 14,
    fontWeight: 600,
    color: "var(--atr-text-muted)",
    textDecoration: "none",
    transition: "color .15s, box-shadow .15s",
    fontFamily: "var(--atr-font-sans)",
    background: "none",
    border: "none",
    cursor: "pointer",
    boxShadow: "inset 0 -3px 0 transparent",
    marginBottom: -1,
  },
  subTabActive: {
    color: "var(--atr-purple)",
    boxShadow: "inset 0 -3px 0 var(--atr-purple)",
  },
  subTabExternal: {
    marginLeft: "auto",
    color: "var(--atr-text)",
    background: "var(--atr-bg-soft)",
    borderRadius: 999,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 600,
    borderBottom: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },

  /* ===== Hero block (icon + title + subtitle + search) ===== */
  hero: {
    background: "linear-gradient(180deg, #F0EDFF 0%, #F8F7FE 100%)",
    borderBottom: "1px solid var(--atr-outline)",
    position: "relative",
    overflow: "hidden",
  },
  heroInner: {
    maxWidth: 1376,
    margin: "0 auto",
    padding: "44px 32px 36px",
    position: "relative",
  },
  heroGrid: {
    display: "grid",
    gridTemplateColumns: "1.2fr 1fr",
    gap: 56,
    alignItems: "center",
  },
  heroLeft: { position: "relative", zIndex: 2 },
  heroRight: { position: "relative", height: 380 },
  heroBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    color: "var(--atr-text)",
    fontSize: 12,
    fontWeight: 700,
    padding: "6px 14px",
    borderRadius: 999,
    letterSpacing: "0.04em",
    marginBottom: 16,
    textTransform: "uppercase",
    boxShadow: "0 2px 8px rgba(31,27,51,0.04)",
  },
  heroTitle: {
    fontSize: 62,
    lineHeight: 0.98,
    fontWeight: 800,
    letterSpacing: "-0.025em",
    color: "var(--atr-text)",
    margin: "0 0 14px",
  },
  heroSubtitle: {
    fontSize: 17,
    lineHeight: 1.5,
    color: "var(--atr-text-muted)",
    margin: "0 0 22px",
    maxWidth: 560,
  },
  heroStatRow: {
    display: "flex",
    gap: 12,
    marginTop: 22,
    flexWrap: "wrap",
  },
  heroStatCard: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 12,
    padding: "10px 14px",
    boxShadow: "0 2px 8px rgba(31,27,51,0.04)",
  },
  heroStatIcon: {
    width: 32, height: 32, borderRadius: 8, background: "rgba(112,104,213,0.12)",
    display: "inline-flex", alignItems: "center", justifyContent: "center",
    fontSize: 16,
  },
  heroStatVal: { fontSize: 14, fontWeight: 800, color: "var(--atr-text)", lineHeight: 1 },
  heroStatLabel: { fontSize: 11, color: "var(--atr-text-muted)", marginTop: 3 },
  heroBlob: { position: "absolute", top: -120, right: -80, pointerEvents: "none", zIndex: 0 },

  /* Collage on right side */
  collage: { position: "absolute", inset: 0 },
  collageImg1: {
    position: "absolute",
    top: 0,
    right: 0,
    width: "70%",
    height: "78%",
    objectFit: "cover",
    borderRadius: 22,
    boxShadow: "0 24px 48px rgba(31,27,51,0.18)",
  },
  collageImg2: {
    position: "absolute",
    bottom: 0,
    left: 0,
    width: "55%",
    height: "55%",
    objectFit: "cover",
    borderRadius: 18,
    boxShadow: "0 18px 36px rgba(31,27,51,0.14)",
    border: "5px solid #fff",
  },
  collageImg3: {
    position: "absolute",
    top: "45%",
    right: "55%",
    width: "30%",
    height: "30%",
    objectFit: "cover",
    borderRadius: 14,
    boxShadow: "0 12px 24px rgba(31,27,51,0.12)",
    border: "4px solid #fff",
  },
  collageRatingPill: {
    position: "absolute",
    top: 24,
    left: -20,
    background: "#fff",
    borderRadius: 14,
    padding: "12px 16px",
    boxShadow: "0 14px 32px rgba(31,27,51,0.18)",
    display: "flex",
    alignItems: "center",
    gap: 10,
    zIndex: 3,
  },
  collageDealPill: {
    position: "absolute",
    bottom: 12,
    right: 0,
    background: "#fff",
    borderRadius: 14,
    padding: "12px 14px",
    boxShadow: "0 14px 32px rgba(31,27,51,0.18)",
    zIndex: 3,
    minWidth: 150,
  },

  /* ===== Hero search bar (input + Cari only) ===== */
  heroSearchWrap: {
    display: "flex",
    alignItems: "center",
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: "8px 8px 8px 24px",
    gap: 12,
    boxShadow: "0 4px 16px rgba(31,27,51,0.06)",
    position: "relative",
    maxWidth: 540,
    marginTop: 4,
  },

  /* ===== Grid toolbar (filter + sort row, near grid) ===== */
  toolbar: {
    maxWidth: 1376,
    margin: "0 auto",
    padding: "8px 32px 0",
  },
  toolbarInner: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    padding: "10px 14px",
    boxShadow: "0 2px 8px rgba(31,27,51,0.04)",
  },
  toolbarLeft: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  toolbarCount: { fontSize: 13, color: "var(--atr-text-muted)", fontWeight: 500, padding: "0 4px" },
  toolbarDivider: { width: 1, height: 24, background: "var(--atr-outline)" },
  toolbarPill: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "var(--atr-bg-soft)",
    color: "var(--atr-text)",
    border: "1px solid transparent",
    borderRadius: 999,
    padding: "9px 16px",
    fontSize: 13,
    fontWeight: 600,
    fontFamily: "var(--atr-font-sans)",
    cursor: "pointer",
    whiteSpace: "nowrap",
    position: "relative",
  },
  searchInputWrap: {
    flex: 1,
    minWidth: 320,
    display: "flex",
    alignItems: "center",
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: "6px 6px 6px 22px",
    gap: 12,
    boxShadow: "0 2px 8px rgba(31,27,51,0.04)",
    position: "relative",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 15,
    fontFamily: "var(--atr-font-sans)",
    color: "var(--atr-text)",
    padding: "10px 0",
  },
  searchClear: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    color: "var(--atr-text-muted)",
    fontSize: 18,
    padding: 4,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtn: {
    background: "var(--atr-purple)",
    color: "#fff",
    border: "none",
    borderRadius: 999,
    padding: "11px 28px",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "var(--atr-font-sans)",
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(112,104,213,0.3)",
  },
  pillBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    color: "var(--atr-purple)",
    border: "1.5px solid var(--atr-purple)",
    borderRadius: 999,
    padding: "11px 22px",
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "var(--atr-font-sans)",
    cursor: "pointer",
    position: "relative",
    whiteSpace: "nowrap",
  },
  pillBtnActive: {
    background: "rgba(112,104,213,0.12)",
  },
  pillCount: {
    background: "var(--atr-purple)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
    minWidth: 18,
    height: 18,
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 5px",
  },

  /* ===== Active chips row ===== */
  chipsRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 18,
    alignItems: "center",
  },
  chipsLabel: { fontSize: 12, color: "var(--atr-text-muted)", fontWeight: 600, letterSpacing: "0.04em", textTransform: "uppercase", marginRight: 4 },
  activeChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "#fff",
    border: "1px solid var(--atr-purple)",
    color: "var(--atr-purple)",
    borderRadius: 999,
    padding: "6px 12px",
    fontSize: 12,
    fontWeight: 600,
  },
  chipX: { cursor: "pointer", fontSize: 14, lineHeight: 1, opacity: 0.7 },
  clearAllBtn: {
    background: "transparent",
    border: "none",
    color: "var(--atr-text-muted)",
    fontSize: 12,
    fontWeight: 600,
    textDecoration: "underline",
    cursor: "pointer",
  },

  /* ===== Grid section ===== */
  gridSection: { maxWidth: 1376, margin: "0 auto", padding: "32px 32px 24px" },
  gridHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 16,
    gap: 20,
  },
  gridTitle: { fontSize: 22, fontWeight: 700, color: "var(--atr-text)", margin: 0 },
  gridSub: { fontSize: 14, color: "var(--atr-text-muted)", margin: "4px 0 0" },
  gridResultCount: { fontSize: 13, color: "var(--atr-text-muted)" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 22,
  },
  paginationRow: { display: "flex", flexDirection: "column", alignItems: "center", gap: 10, padding: "40px 0 16px" },
  loadMore: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    background: "#fff",
    color: "var(--atr-text)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: "12px 28px",
    fontSize: 14,
    fontWeight: 600,
    fontFamily: "var(--atr-font-sans)",
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(31,27,51,0.05)",
  },
  pageInfo: { fontSize: 12, color: "var(--atr-text-muted)" },

  /* ===== Product card ===== */
  card: {
    background: "#fff",
    borderRadius: 16,
    border: "1px solid var(--atr-outline)",
    overflow: "hidden",
    cursor: "pointer",
    transition: "transform .18s, box-shadow .18s",
    display: "flex",
    flexDirection: "column",
    position: "relative",
  },
  cardHover: { transform: "translateY(-4px)", boxShadow: "0 18px 36px rgba(31,27,51,0.12)", border: "1px solid var(--atr-purple-light, #CDCDED)" },
  cardImgWrap: { position: "relative", aspectRatio: "4 / 3", overflow: "hidden", background: "var(--atr-bg-soft)" },
  cardImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  cardPill: {
    position: "absolute",
    top: 12,
    left: 12,
    background: "#fff",
    color: "var(--atr-text)",
    fontSize: 11,
    fontWeight: 700,
    padding: "5px 12px",
    borderRadius: 999,
    letterSpacing: "0.02em",
    boxShadow: "0 2px 6px rgba(0,0,0,0.08)",
  },
  cardPillBest: { background: "linear-gradient(135deg, #FFC442 0%, #FFB020 100%)", color: "#3D2900" },
  cardPillNew: { background: "var(--atr-purple)", color: "#fff" },
  cardDiscountBadge: {
    position: "absolute",
    top: 46,
    left: 12,
    background: "var(--atr-red)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 800,
    padding: "4px 10px",
    borderRadius: 6,
    letterSpacing: "0.04em",
    boxShadow: "0 2px 6px rgba(196,73,73,0.32)",
  },
  cardSave: {
    position: "absolute",
    top: 10,
    right: 10,
    width: 34, height: 34,
    borderRadius: 999,
    background: "rgba(255,255,255,0.92)",
    border: "none",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 2px 6px rgba(0,0,0,0.1)",
    backdropFilter: "blur(4px)",
  },
  cardHotPill: {
    position: "absolute",
    bottom: 12,
    left: 12,
    background: "rgba(31,27,51,0.85)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 600,
    padding: "5px 10px",
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    backdropFilter: "blur(6px)",
  },
  cardHoverCta: {
    position: "absolute",
    bottom: 12,
    right: 12,
    background: "var(--atr-purple)",
    color: "#fff",
    fontSize: 11,
    fontWeight: 700,
    padding: "6px 12px",
    borderRadius: 999,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    transition: "opacity .15s, transform .15s",
    boxShadow: "0 4px 12px rgba(112,104,213,0.5)",
  },
  cardBody: { padding: "14px 14px 14px", display: "flex", flexDirection: "column", gap: 6, flex: 1 },
  cardRegion: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11.5, color: "var(--atr-text-muted)", fontWeight: 500, flexWrap: "wrap" },
  cardRegionPin: {
    width: 16, height: 16, borderRadius: 999, background: "var(--atr-purple)",
    display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0,
  },
  cardTitle: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)", lineHeight: 1.3, margin: "2px 0 4px", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden", textOverflow: "ellipsis", minHeight: 39 },

  /* Feature chips (Konfirmasi cepat / Free cancel / fasilitas) */
  cardChips: { display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 4 },
  cardChipFeature: {
    display: "inline-flex", alignItems: "center", gap: 4,
    background: "rgba(81,176,84,0.12)", color: "#1F5E2A",
    fontSize: 10, fontWeight: 700, padding: "3px 8px", borderRadius: 999, letterSpacing: "0.01em",
  },
  cardChipFacility: {
    background: "var(--atr-bg-soft)", color: "var(--atr-text)",
    fontSize: 10, fontWeight: 600, padding: "3px 8px", borderRadius: 999,
    border: "1px solid var(--atr-outline)",
  },

  /* Rating row */
  cardRatingRow: { display: "flex", alignItems: "center", gap: 8, marginTop: 2 },
  cardRatingBox: {
    display: "inline-flex", alignItems: "center", gap: 4,
    background: "var(--atr-bg-soft)", padding: "3px 9px", borderRadius: 6,
    fontSize: 12, color: "var(--atr-text)",
  },
  cardReviews: { fontSize: 11, color: "var(--atr-text-muted)" },

  /* Price row */
  cardPriceRow: { display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 6, marginTop: 6, paddingTop: 4 },
  cardPriceLabel: { fontSize: 10, color: "var(--atr-text-muted)", fontWeight: 600 },
  cardPrice: { fontSize: 18, fontWeight: 800, color: "var(--atr-red)", lineHeight: 1, letterSpacing: "-0.01em" },
  cardPriceUnit: { fontSize: 11, color: "var(--atr-text-muted)", paddingBottom: 1 },
  cardPriceStrike: { fontSize: 11, color: "var(--atr-text-muted)", textDecoration: "line-through", marginBottom: 1 },

  cardDivider: { borderTop: "1px solid var(--atr-outline)", margin: "10px 0 0" },
  cardOperator: { display: "flex", alignItems: "center", gap: 8, paddingTop: 10, fontSize: 11.5, color: "var(--atr-text-muted)" },
  cardOperatorAvatar: { width: 22, height: 22, borderRadius: 999, objectFit: "cover", flexShrink: 0, background: "var(--atr-bg-soft)" },
  cardOperatorVerify: { display: "inline-flex", flexShrink: 0 },

  /* Attraction-specific */
  cardCatChip: {
    position: "absolute",
    bottom: 12,
    left: 12,
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: "#fff",
    fontSize: 10.5,
    fontWeight: 700,
    padding: "4px 10px",
    borderRadius: 999,
    boxShadow: "0 2px 6px rgba(0,0,0,0.08)",
  },
  attrPriceBlock: {
    marginTop: 8,
    paddingTop: 8,
    borderTop: "1px solid var(--atr-outline)",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  attrStrikeRow: { display: "flex", alignItems: "center", gap: 8 },
  attrSavedPill: {
    background: "rgba(196,73,73,0.12)",
    color: "var(--atr-red)",
    fontSize: 10,
    fontWeight: 700,
    padding: "2px 7px",
    borderRadius: 4,
    letterSpacing: "0.02em",
  },

  /* Attraction grid, 5 cols */
  gridAttr: {
    display: "grid",
    gridTemplateColumns: "repeat(5, 1fr)",
    gap: 18,
  },

  /* ===== Dropdown menu (sort) ===== */
  dropdown: {
    position: "absolute",
    top: "calc(100% + 8px)",
    right: 0,
    background: "#fff",
    borderRadius: 14,
    border: "1px solid var(--atr-outline)",
    boxShadow: "0 12px 32px rgba(31,27,51,0.14)",
    minWidth: 240,
    padding: 8,
    zIndex: 60,
  },
  dropdownItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 10,
    cursor: "pointer",
    fontSize: 14,
    color: "var(--atr-text)",
    fontWeight: 500,
    background: "none",
    border: "none",
    width: "100%",
    textAlign: "left",
    fontFamily: "var(--atr-font-sans)",
  },
  radio: {
    width: 18, height: 18, borderRadius: 999, border: "1.5px solid var(--atr-outline)", flexShrink: 0,
    display: "inline-flex", alignItems: "center", justifyContent: "center",
  },
  radioOn: { border: "1.5px solid var(--atr-purple)" },
  radioDot: { width: 10, height: 10, borderRadius: 999, background: "var(--atr-purple)" },

  /* ===== Modal scrim ===== */
  scrim: {
    position: "fixed",
    inset: 0,
    background: "rgba(31,27,51,0.45)",
    backdropFilter: "blur(2px)",
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modal: {
    background: "#fff",
    borderRadius: 18,
    width: "100%",
    maxWidth: 720,
    maxHeight: "85vh",
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 24px 64px rgba(31,27,51,0.3)",
  },
  modalHeader: {
    display: "flex",
    alignItems: "center",
    padding: "20px 24px",
    borderBottom: "1px solid var(--atr-outline)",
    gap: 12,
  },
  modalTitle: { fontSize: 17, fontWeight: 700, color: "var(--atr-text)", margin: 0, flex: 1, textAlign: "center" },
  modalCloseBtn: {
    background: "transparent", border: "none", cursor: "pointer", padding: 6, display: "inline-flex",
    borderRadius: 8,
  },
  modalGhostBtn: {
    background: "transparent", border: "none", cursor: "pointer", color: "var(--atr-text-muted)",
    fontWeight: 600, fontSize: 14, padding: "8px 14px", fontFamily: "var(--atr-font-sans)",
  },
  modalApplyBtn: {
    background: "var(--atr-purple)", color: "#fff", border: "none", borderRadius: 10,
    padding: "10px 22px", fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)",
    boxShadow: "0 4px 12px rgba(112,104,213,0.3)",
  },
  modalBody: { padding: "20px 24px", overflowY: "auto", flex: 1 },
  modalFooter: {
    padding: "14px 24px",
    borderTop: "1px solid var(--atr-outline)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    background: "var(--atr-bg-soft, #F8F7FE)",
  },
  modalSection: { marginBottom: 26 },
  modalSectionTitle: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)", marginBottom: 12, display: "flex", alignItems: "center", justifyContent: "space-between" },

  /* Chip selector */
  chipGrid: { display: "flex", flexWrap: "wrap", gap: 8 },
  chipSelect: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    background: "#fff",
    color: "var(--atr-text)",
    border: "1px solid var(--atr-outline)",
    borderRadius: 999,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
    transition: "all .15s",
  },
  chipSelectOn: {
    background: "var(--atr-purple-light, #CDCDED)",
    color: "var(--atr-purple)",
    border: "1px solid var(--atr-purple)",
    fontWeight: 700,
  },

  /* Number input pair */
  numPair: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  numInputWrap: {
    border: "1.5px solid var(--atr-outline)",
    borderRadius: 10,
    padding: "10px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  numInputLabel: { fontSize: 11, color: "var(--atr-text-muted)", fontWeight: 600 },
  numInput: { border: "none", outline: "none", background: "transparent", fontSize: 16, fontWeight: 600, color: "var(--atr-text)", fontFamily: "var(--atr-font-sans)", width: "100%" },

  /* Range slider */
  rangeWrap: { position: "relative", margin: "20px 0 12px", height: 24, display: "flex", alignItems: "center" },
  rangeTrack: { position: "absolute", left: 0, right: 0, height: 4, borderRadius: 999, background: "var(--atr-outline)" },
  rangeFill: { position: "absolute", height: 4, borderRadius: 999, background: "var(--atr-purple)" },
  rangeKnob: { position: "absolute", width: 22, height: 22, borderRadius: 999, background: "#fff", border: "2px solid var(--atr-purple)", boxShadow: "0 2px 6px rgba(0,0,0,0.12)", transform: "translateX(-50%)", cursor: "pointer", top: 1 },

  /* Search dropdown (autocomplete results) */
  searchResults: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    right: 0,
    background: "#fff",
    borderRadius: 16,
    border: "1px solid var(--atr-outline)",
    boxShadow: "0 16px 40px rgba(31,27,51,0.14)",
    padding: 8,
    maxHeight: 380,
    overflowY: "auto",
    zIndex: 30,
  },
  searchHeader: { fontSize: 12, color: "var(--atr-text-muted)", padding: "8px 12px", fontWeight: 600 },
  searchResultItem: {
    display: "flex", alignItems: "center", gap: 14, padding: "10px 12px", borderRadius: 10, cursor: "pointer",
    textAlign: "left", border: "none", background: "transparent", width: "100%", fontFamily: "var(--atr-font-sans)",
  },
  searchResultThumb: { width: 52, height: 52, borderRadius: 10, objectFit: "cover", flexShrink: 0, background: "var(--atr-bg-soft)" },
  searchResultTitle: { fontSize: 14, fontWeight: 600, color: "var(--atr-text)" },
  searchResultMeta: { fontSize: 12, color: "var(--atr-text-muted)", display: "inline-flex", alignItems: "center", gap: 4, marginTop: 2 },

  /* Promo strip (top of header) */
  promoStrip: {
    background: "#FFF6E3",
    borderBottom: "1px solid #F4E5BB",
    fontSize: 13,
    color: "#5C4400",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: 10,
    padding: "8px 16px",
    fontWeight: 500,
  },

  /* ===== Category rail ===== */
  catRail: { maxWidth: 1376, margin: "0 auto", padding: "40px 32px 8px" },
  catRailHeader: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", marginBottom: 18 },
  catRailTitle: { fontSize: 22, fontWeight: 800, color: "var(--atr-text)", margin: 0, letterSpacing: "-0.01em" },
  catRailMore: {
    background: "transparent", border: "none", color: "var(--atr-purple)",
    fontSize: 14, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)",
  },
  catRailGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(8, 1fr)",
    gap: 12,
  },
  catTile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    background: "#fff",
    border: "1px solid var(--atr-outline)",
    borderRadius: 14,
    padding: "16px 8px 14px",
    cursor: "pointer",
    transition: "transform .15s, box-shadow .15s",
    fontFamily: "var(--atr-font-sans)",
  },
  catTileIconWrap: {
    width: 52, height: 52, borderRadius: 14,
    display: "inline-flex", alignItems: "center", justifyContent: "center",
  },
  catTileEmoji: { fontSize: 26, lineHeight: 1 },
  catTileLabel: { fontSize: 13, fontWeight: 700, color: "var(--atr-text)", textAlign: "center" },
  catTileCount: { fontSize: 11, color: "var(--atr-text-muted)" },

  /* ===== Promo banners section ===== */
  promoSection: { maxWidth: 1376, margin: "0 auto", padding: "24px 32px" },
  promoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 18,
  },
  promoCard: {
    position: "relative",
    borderRadius: 18,
    padding: "26px 24px 22px",
    minHeight: 168,
    overflow: "hidden",
    display: "flex",
    alignItems: "flex-start",
    cursor: "pointer",
    transition: "transform .2s, box-shadow .2s",
  },
  promoEyebrow: {
    fontSize: 11, fontWeight: 800, letterSpacing: "0.12em", textTransform: "uppercase",
    opacity: 0.7, marginBottom: 8,
  },
  promoTitle: {
    fontSize: 22, fontWeight: 800, margin: "0 0 6px", letterSpacing: "-0.01em", lineHeight: 1.15,
    maxWidth: 220,
  },
  promoSub: { fontSize: 13, opacity: 0.78, margin: "0 0 14px", lineHeight: 1.4, maxWidth: 240 },
  promoBtn: {
    display: "inline-flex", alignItems: "center", gap: 6,
    background: "rgba(255,255,255,0.65)",
    border: "1.5px solid currentColor",
    borderRadius: 999,
    padding: "8px 16px",
    fontSize: 13, fontWeight: 700,
    cursor: "pointer",
    fontFamily: "var(--atr-font-sans)",
  },
  promoEmoji: {
    position: "absolute", right: 22, bottom: 16, fontSize: 64, opacity: 0.85, zIndex: 1,
  },
  promoBlob: { position: "absolute", inset: 0, width: "100%", height: "100%", zIndex: 0 },
};
