export const ps = {
  page: { background: "var(--atr-bg-soft)", minHeight: "100vh", fontFamily: "var(--atr-font-sans)", color: "var(--atr-text)" },
  shell: { maxWidth: 1280, margin: "0 auto", padding: "10px 24px 64px" },
  layout: { display: "grid", gridTemplateColumns: "300px 1fr", gap: 24, alignItems: "start", marginTop: 14 },

  /* ---------- SIDEBAR ---------- */
  side: { display: "flex", flexDirection: "column", gap: 16, position: "sticky", top: 90 },
  profCard: {
    background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 18, boxShadow: "var(--atr-shadow-2)",
    overflow: "hidden",
  },
  profCover: { height: 76, background: "linear-gradient(135deg, #6E62D8 0%, #8B6FD0 55%, #9B6AAB 100%)", position: "relative" },
  profCoverBlob: { position: "absolute", borderRadius: "50%", background: "rgba(255,255,255,0.16)" },
  profBody: { padding: "0 20px 22px", textAlign: "center", marginTop: -34, position: "relative", zIndex: 2 },
  profAvatar: { width: 72, height: 72, borderRadius: 999, objectFit: "cover", margin: "0 auto", display: "block", border: "4px solid #fff", boxShadow: "var(--atr-shadow-2)", position: "relative", zIndex: 2 },
  profName: { fontSize: 19, fontWeight: 700, color: "var(--atr-text)", marginTop: 10, letterSpacing: "-0.01em" },
  profTier: {
    display: "inline-flex", alignItems: "center", gap: 6, marginTop: 8,
    background: "linear-gradient(135deg, #FFF3D1, #FFE7A8)", border: "1px solid rgba(255,196,66,0.5)", borderRadius: 999,
    padding: "5px 14px", fontSize: 12.5, fontWeight: 800, color: "#9A6A00",
  },
  profPtsRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginTop: 18, marginBottom: 7 },
  profPtsLabel: { fontSize: 12, fontWeight: 700, color: "var(--atr-text)" },
  profPtsNext: { fontSize: 11.5, color: "var(--atr-text-muted)" },
  profBar: { height: 7, borderRadius: 999, background: "var(--atr-bg-cool)", overflow: "hidden" },
  profBarFill: { height: "100%", borderRadius: 999, background: "linear-gradient(90deg, var(--atr-purple), #9B6AAB)" },
  profStats: { display: "flex", marginTop: 18, borderTop: "1px solid var(--atr-outline)", paddingTop: 16 },
  profStat: { flex: 1, textAlign: "center" },
  profStatVal: { fontSize: 18, fontWeight: 800, color: "var(--atr-text)" },
  profStatLabel: { fontSize: 11, color: "var(--atr-text-muted)", marginTop: 2, fontWeight: 600 },
  profStatDiv: { width: 1, background: "var(--atr-outline)", margin: "2px 0" },

  navGroup: { background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 18, boxShadow: "var(--atr-shadow-2)", padding: 12 },
  navLabel: { fontSize: 11, fontWeight: 800, color: "var(--atr-text-muted)", textTransform: "uppercase", letterSpacing: "0.1em", padding: "6px 10px 8px" },
  navItem: {
    display: "flex", alignItems: "center", gap: 12, padding: "9px 12px", borderRadius: 12,
    fontSize: 14.5, fontWeight: 600, color: "var(--atr-text)", cursor: "pointer",
    background: "transparent", border: "none", width: "100%", fontFamily: "var(--atr-font-sans)", textAlign: "left",
    transition: "background .14s, color .14s", position: "relative",
  },
  navItemActive: { background: "var(--atr-purple-50)", color: "var(--atr-purple)", fontWeight: 700 },
  navItemIcon: { width: 34, height: 34, borderRadius: 10, display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, background: "var(--atr-bg-soft)", color: "var(--atr-text-muted)", transition: "background .14s, color .14s" },
  navItemIconActive: { background: "var(--atr-purple)", color: "#fff" },
  navChevron: { marginLeft: "auto", color: "var(--atr-purple)" },

  logout: {
    background: "#fff", color: "var(--atr-red)", border: "1.5px solid var(--atr-red)", borderRadius: 14,
    padding: "13px 16px", fontSize: 14.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)",
    display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 8, width: "100%",
  },

  /* ---------- MAIN PANEL ---------- */
  panel: { background: "#fff", border: "1px solid var(--atr-outline)", borderRadius: 18, boxShadow: "var(--atr-shadow-2)", padding: 28, minHeight: 600 },
  panelHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 16, flexWrap: "wrap" },
  h1: { fontSize: 25, fontWeight: 700, color: "var(--atr-text)", letterSpacing: "-0.02em" },
  sub: { fontSize: 13.5, color: "var(--atr-text-muted)", marginTop: 5 },

  /* buttons */
  btnPrimary: {
    background: "var(--atr-purple)", color: "#fff", border: "none", borderRadius: 10, padding: "11px 20px",
    fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)",
    display: "inline-flex", alignItems: "center", gap: 8, boxShadow: "0 4px 12px rgba(112,104,213,0.28)",
  },
  btnGhost: {
    background: "#fff", color: "var(--atr-text)", border: "1px solid var(--atr-outline)", borderRadius: 10, padding: "11px 18px",
    fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)",
    display: "inline-flex", alignItems: "center", gap: 8,
  },
  btnDanger: {
    background: "#fff", color: "var(--atr-red)", border: "1.5px solid var(--atr-red)", borderRadius: 10, padding: "11px 18px",
    fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)",
    display: "inline-flex", alignItems: "center", gap: 8,
  },
  linkBtn: { background: "none", border: "none", color: "var(--atr-purple)", fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)", padding: 0 },

  /* ---------- PROFIL SAYA, banner + grouped data sheet ---------- */
  banner: { position: "relative", borderRadius: 18, overflow: "hidden", marginBottom: 26, border: "1px solid var(--atr-outline)" },
  bannerCover: { height: 128, background: "linear-gradient(135deg, #6E62D8 0%, #8B6FD0 55%, #9B6AAB 100%)", position: "relative" },
  bannerImg: { position: "absolute", inset: 0, width: "100%", height: "100%", objectFit: "cover", opacity: 0.32 },
  bannerEditCover: { position: "absolute", top: 14, right: 14, zIndex: 3, background: "rgba(255,255,255,0.92)", border: "none", borderRadius: 999, padding: "8px 14px", fontSize: 12.5, fontWeight: 700, color: "var(--atr-text)", cursor: "pointer", fontFamily: "var(--atr-font-sans)", display: "inline-flex", alignItems: "center", gap: 7 },
  bannerAvatar: { position: "absolute", left: 24, top: 80, zIndex: 3, width: 96, height: 96, borderRadius: 24, objectFit: "cover", border: "4px solid #fff", boxShadow: "var(--atr-shadow-2)" },
  bannerBody: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18, padding: "16px 24px 14px 140px", minHeight: 60, background: "#fff" },
  bannerName: { fontSize: 24, fontWeight: 700, color: "var(--atr-text)", letterSpacing: "-0.02em" },
  bannerMeta: { fontSize: 13, color: "var(--atr-text-muted)", marginTop: 3, display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  bannerMetaDot: { width: 3, height: 3, borderRadius: 999, background: "var(--atr-text-muted)" },

  complete: { display: "flex", alignItems: "center", gap: 14, background: "var(--atr-purple-50)", border: "1px solid var(--atr-purple-light)", borderRadius: 14, padding: "14px 18px", marginBottom: 26 },
  completeRing: { flexShrink: 0 },
  completeTitle: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)" },
  completeText: { fontSize: 12.5, color: "var(--atr-text-muted)", marginTop: 2 },

  dataSection: { marginTop: 8 },
  dataSecHead: { display: "flex", alignItems: "center", gap: 10, margin: "22px 0 6px" },
  dataSecIcon: { width: 30, height: 30, borderRadius: 9, background: "var(--atr-purple-50)", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  dataSecTitle: { fontSize: 15.5, fontWeight: 700, color: "var(--atr-text)" },
  dataList: { border: "1px solid var(--atr-outline)", borderRadius: 14, overflow: "hidden" },
  dataRow: { display: "flex", alignItems: "center", gap: 14, padding: "15px 18px", borderTop: "1px solid var(--atr-outline)" },
  dataRowFirst: { borderTop: "none" },
  dataRowIcon: { width: 20, color: "var(--atr-text-muted)", display: "inline-flex", flexShrink: 0 },
  dataRowLabel: { fontSize: 13.5, color: "var(--atr-text-muted)", fontWeight: 600, width: 168, flexShrink: 0 },
  dataRowVal: { fontSize: 14.5, fontWeight: 700, color: "var(--atr-text)" },

  /* legacy field cards */
  fieldGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginTop: 22 },
  fieldCard: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: "16px 18px", background: "#fff" },
  fieldLabel: { fontSize: 11, fontWeight: 800, color: "var(--atr-text-muted)", textTransform: "uppercase", letterSpacing: "0.06em" },
  fieldVal: { fontSize: 16, fontWeight: 700, color: "var(--atr-text)", marginTop: 8, letterSpacing: "-0.01em" },

  divider: { borderTop: "1px solid var(--atr-outline)", margin: "26px 0" },
  sectionTitle: { fontSize: 19, fontWeight: 700, color: "var(--atr-text)", letterSpacing: "-0.01em" },
  sectionSub: { fontSize: 13, color: "var(--atr-text-muted)", marginTop: 4 },

  chipRow: { display: "flex", flexWrap: "wrap", gap: 10, marginTop: 16 },
  chip: { padding: "8px 18px", borderRadius: 999, fontSize: 13.5, fontWeight: 600, background: "var(--atr-purple-50)", color: "var(--atr-purple)", border: "1px solid var(--atr-purple-light)" },
  chipSelectable: { padding: "8px 18px", borderRadius: 999, fontSize: 13.5, fontWeight: 600, cursor: "pointer", border: "1.5px solid var(--atr-outline)", background: "#fff", color: "var(--atr-text-muted)", fontFamily: "var(--atr-font-sans)", transition: "all .12s" },
  chipSelected: { border: "1.5px solid var(--atr-purple)", background: "var(--atr-purple-50)", color: "var(--atr-purple)" },

  /* ---------- FORMS ---------- */
  formSectionTitle: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)", margin: "22px 0 14px" },
  groupCard: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: 18, background: "#fff", display: "flex", flexDirection: "column", gap: 7 },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 },
  formLabel: { fontSize: 13.5, fontWeight: 600, color: "var(--atr-text)" },
  req: { color: "var(--atr-red)" },
  input: {
    width: "100%", border: "1px solid var(--atr-outline)", borderRadius: 10, padding: "12px 14px",
    fontSize: 14, color: "var(--atr-text)", fontFamily: "var(--atr-font-sans)", background: "var(--atr-bg-soft)", outline: "none", boxSizing: "border-box",
  },
  inputWrap: { position: "relative" },
  eyeBtn: { position: "absolute", right: 10, top: "50%", transform: "translateY(-50%)", background: "none", border: "none", cursor: "pointer", color: "var(--atr-text-muted)", padding: 4, display: "inline-flex" },
  selectChevron: { position: "absolute", right: 14, top: "50%", transform: "translateY(-50%)", pointerEvents: "none", color: "var(--atr-text-muted)" },
  otpNote: { fontSize: 12.5, color: "#C99500", fontWeight: 600, display: "inline-flex", alignItems: "center", gap: 6, marginTop: 2 },
  formActions: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: 24 },

  /* ---------- PENGATURAN sections (2-col) ---------- */
  setRow: { display: "grid", gridTemplateColumns: "260px 1fr", gap: 32, padding: "26px 0", borderTop: "1px solid var(--atr-outline)" },
  setLabel: { fontSize: 18, fontWeight: 700, color: "var(--atr-text)" },
  setLabelDanger: { color: "var(--atr-red)" },
  setDesc: { fontSize: 13, color: "var(--atr-text-muted)", marginTop: 8, lineHeight: 1.5 },
  setCard: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: 22, background: "#fff", position: "relative" },
  setCardHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 4 },
  kvLabel: { fontSize: 12.5, fontWeight: 700, color: "var(--atr-text-muted)" },
  kvVal: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)", marginTop: 4, marginBottom: 18 },
  socialRow: { display: "flex", alignItems: "center", gap: 12, padding: "10px 0" },
  socialIcon: { width: 38, height: 38, borderRadius: 999, display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  socialName: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)" },
  socialHandle: { fontSize: 13, color: "var(--atr-text-muted)", marginTop: 1 },
  dangerCard: { border: "1px solid rgba(244,98,99,0.35)", background: "rgba(244,98,99,0.05)", borderRadius: 14, padding: 22, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 20 },
  dangerTitle: { fontSize: 14.5, fontWeight: 700, color: "var(--atr-text)" },
  dangerText: { fontSize: 13, color: "var(--atr-red)", marginTop: 6, lineHeight: 1.5, maxWidth: 340 },
  dangerBtn: { background: "var(--atr-red)", color: "#fff", border: "none", borderRadius: 10, padding: "12px 20px", fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)", flexShrink: 0, whiteSpace: "nowrap" },
  cardActions: { display: "flex", justifyContent: "flex-end", alignItems: "center", gap: 16, marginTop: 16, paddingTop: 16, borderTop: "1px solid var(--atr-outline)" },

  /* ---------- generic mini tab / search ---------- */
  tabBar: { display: "flex", gap: 4, borderBottom: "1px solid var(--atr-outline)", marginTop: 20, overflowX: "auto" },
  tab: { padding: "12px 16px", border: "none", background: "transparent", fontSize: 14, fontWeight: 600, color: "var(--atr-text-muted)", cursor: "pointer", fontFamily: "var(--atr-font-sans)", borderBottom: "2px solid transparent", whiteSpace: "nowrap" },
  tabActive: { color: "var(--atr-purple)", borderBottom: "2px solid var(--atr-purple)" },
  search: { display: "flex", alignItems: "center", gap: 10, background: "var(--atr-bg-soft)", border: "1px solid var(--atr-outline)", borderRadius: 12, padding: "12px 16px", marginTop: 18 },
  searchInput: { flex: 1, border: "none", background: "transparent", outline: "none", fontSize: 14, color: "var(--atr-text)", fontFamily: "var(--atr-font-sans)" },

  /* ---------- modal ---------- */
  scrim: { position: "fixed", inset: 0, zIndex: 1000, background: "rgba(31,27,51,0.5)", backdropFilter: "blur(3px)", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  modal: { background: "#fff", borderRadius: 18, width: "min(480px, 100%)", boxShadow: "0 30px 70px rgba(31,27,51,0.4)", padding: 24 },
  modalHead: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 },
  modalTitle: { fontSize: 19, fontWeight: 700, color: "var(--atr-text)" },
  modalClose: { background: "none", border: "none", cursor: "pointer", color: "var(--atr-text-muted)", padding: 4, display: "inline-flex" },
  modalActions: { display: "flex", justifyContent: "flex-end", alignItems: "center", gap: 14, marginTop: 22 },
};

export const orderStyles = {
  statGrid: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 14, marginTop: 22 },
  statCard: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: "16px 18px", display: "flex", alignItems: "flex-start", gap: 12, background: "#fff" },
  statIcon: { width: 40, height: 40, borderRadius: 11, display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, color: "#fff" },
  statCount: { fontSize: 26, fontWeight: 800, color: "var(--atr-text)", lineHeight: 1, marginLeft: "auto" },
  statLabel: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)", marginTop: 2 },
  statSub: { fontSize: 11.5, color: "var(--atr-text-muted)", marginTop: 3 },

  card: { display: "grid", gridTemplateColumns: "200px 1fr", border: "1px solid var(--atr-outline)", borderRadius: 16, overflow: "hidden", marginTop: 16, boxShadow: "var(--atr-shadow-1)" },
  cardImgWrap: { position: "relative", minHeight: 170 },
  cardImg: { width: "100%", height: "100%", minHeight: 170, objectFit: "cover", display: "block" },
  cardBody: { padding: 20, display: "flex", flexDirection: "column" },
  cardTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  cardCode: { fontSize: 12, fontWeight: 800, color: "var(--atr-text-muted)", letterSpacing: "0.04em" },
  cardTitle: { fontSize: 17, fontWeight: 700, color: "var(--atr-text)", marginTop: 8, lineHeight: 1.3, letterSpacing: "-0.01em" },
  cardPriceLabel: { fontSize: 12, color: "var(--atr-text-muted)", marginTop: 14 },
  cardPrice: { fontSize: 17, fontWeight: 800, color: "var(--atr-text)", marginTop: 3 },
  cardFoot: { display: "flex", justifyContent: "flex-end", gap: 10, marginTop: "auto", paddingTop: 16, borderTop: "1px solid var(--atr-outline)" },
  badge: { display: "inline-flex", alignItems: "center", gap: 6, padding: "5px 12px", borderRadius: 999, fontSize: 12, fontWeight: 700, whiteSpace: "nowrap" },
  payBtn: { background: "var(--atr-yellow)", color: "#7A5A00", border: "none", borderRadius: 9, padding: "9px 18px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)" },

  /* empty state */
  empty: { textAlign: "center", padding: "60px 20px" },
  emptyIcon: { width: 84, height: 84, borderRadius: 999, background: "var(--atr-bg-soft)", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "var(--atr-text-muted)", marginBottom: 18 },
  emptyTitle: { fontSize: 18, fontWeight: 700, color: "var(--atr-text)" },
  emptyText: { fontSize: 14, color: "var(--atr-text-muted)", marginTop: 6 },

  /* review modal */
  reviewModal: { background: "#fff", borderRadius: 20, width: "min(680px, 100%)", maxHeight: "calc(100vh - 48px)", display: "flex", flexDirection: "column", boxShadow: "0 30px 70px rgba(31,27,51,0.4)" },
  rmHead: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", padding: "24px 28px 18px", borderBottom: "1px solid var(--atr-outline)" },
  rmTitle: { fontSize: 22, fontWeight: 700, color: "var(--atr-text)", letterSpacing: "-0.01em" },
  rmSub: { fontSize: 13.5, color: "var(--atr-text-muted)", marginTop: 3 },
  rmBody: { padding: "20px 28px", overflowY: "auto", display: "flex", flexDirection: "column", gap: 22 },
  rmSecTitle: { fontSize: 15, fontWeight: 700, color: "var(--atr-text)", marginBottom: 12 },
  tripChips: { display: "flex", flexWrap: "wrap", gap: 10 },
  tripChip: { padding: "9px 18px", borderRadius: 999, fontSize: 13.5, fontWeight: 600, cursor: "pointer", border: "1.5px solid var(--atr-outline)", background: "#fff", color: "var(--atr-text)", fontFamily: "var(--atr-font-sans)", transition: "all .12s" },
  tripChipOn: { border: "1.5px solid var(--atr-purple)", background: "var(--atr-purple-50)", color: "var(--atr-purple)" },
  catGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 },
  catCard: { background: "var(--atr-bg-soft)", border: "1px solid var(--atr-outline)", borderRadius: 14, padding: "16px 18px" },
  catLabel: { fontSize: 14.5, fontWeight: 700, color: "var(--atr-text)", marginBottom: 10 },
  starRow: { display: "flex", gap: 6 },
  starBtn: { background: "none", border: "none", padding: 0, cursor: "pointer", display: "inline-flex", lineHeight: 0 },
  rmTextarea: { width: "100%", minHeight: 120, border: "1px solid var(--atr-outline)", borderRadius: 12, padding: "14px 16px", fontSize: 14, color: "var(--atr-text)", fontFamily: "var(--atr-font-sans)", background: "var(--atr-bg-soft)", outline: "none", resize: "vertical", boxSizing: "border-box" },
  rmFoot: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14, padding: "18px 28px", borderTop: "1px solid var(--atr-outline)" },
  rmCancel: { background: "#fff", color: "var(--atr-purple)", border: "1.5px solid var(--atr-purple)", borderRadius: 12, padding: "13px 18px", fontSize: 14.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)" },
  rmSubmit: { background: "var(--atr-purple)", color: "#fff", border: "none", borderRadius: 12, padding: "13px 18px", fontSize: 14.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)", boxShadow: "0 6px 16px rgba(112,104,213,0.3)" },
};

export const wishStyles = {
  collGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(220px,1fr))", gap: 20, marginTop: 22 },
  collCard: { border: "1px solid var(--atr-outline)", borderRadius: 16, overflow: "hidden", background: "#fff", cursor: "pointer", boxShadow: "var(--atr-shadow-1)", transition: "transform .15s, box-shadow .15s" },
  mosaic: { display: "grid", gridTemplateColumns: "1fr 1fr", gridTemplateRows: "1fr 1fr", height: 150, gap: 2, background: "var(--atr-outline)" },
  mosaicCell: { overflow: "hidden", background: "var(--atr-bg-cool)" },
  mosaicImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  mosaicEmpty: { display: "flex", alignItems: "center", justifyContent: "center", color: "var(--atr-text-muted)", fontSize: 11 },
  specialMosaic: { background: "var(--atr-bg-cool)", display: "grid", gridTemplateColumns: "1fr 1fr", gridTemplateRows: "1fr 1fr", height: 150, gap: 2 },
  specialCell: { display: "flex", alignItems: "center", justifyContent: "center", background: "#E9EBFA", color: "var(--atr-purple-soft)" },
  collBody: { padding: 16 },
  collName: { fontSize: 16, fontWeight: 700, color: "var(--atr-text)" },
  collCount: { fontSize: 13, color: "var(--atr-text-muted)", marginTop: 3 },
  createCard: { border: "2px dashed var(--atr-outline)", borderRadius: 16, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 12, minHeight: 218, cursor: "pointer", color: "var(--atr-text-muted)", background: "var(--atr-bg-soft)" },
  createIcon: { width: 52, height: 52, borderRadius: 999, border: "1.5px solid var(--atr-outline)", display: "inline-flex", alignItems: "center", justifyContent: "center", background: "#fff" },

  detailHead: { display: "flex", alignItems: "center", gap: 16, marginBottom: 4 },
  backBtn: { width: 40, height: 40, borderRadius: 999, border: "1px solid var(--atr-outline)", background: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "var(--atr-text)", flexShrink: 0 },
  detailTitle: { fontSize: 24, fontWeight: 700, color: "var(--atr-text)", letterSpacing: "-0.02em" },
  detailSub: { fontSize: 13.5, color: "var(--atr-text-muted)", marginTop: 3 },

  prodGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px,1fr))", gap: 20, marginTop: 24 },
  prodCard: { border: "1px solid var(--atr-outline)", borderRadius: 16, overflow: "hidden", background: "#fff", boxShadow: "var(--atr-shadow-1)", display: "flex", flexDirection: "column" },
  prodMedia: { position: "relative", height: 168 },
  prodImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  prodMenu: { position: "absolute", top: 12, right: 12, width: 34, height: 34, borderRadius: 999, background: "rgba(255,255,255,0.95)", border: "none", display: "inline-flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "var(--atr-text)", boxShadow: "0 2px 8px rgba(0,0,0,0.18)" },
  prodBody: { padding: 16, display: "flex", flexDirection: "column", gap: 8, flex: 1 },
  prodMetaRow: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 },
  prodCity: { display: "inline-flex", alignItems: "center", gap: 6, fontSize: 13, fontWeight: 600, color: "var(--atr-text)" },
  prodCityPin: { width: 22, height: 22, borderRadius: 999, background: "var(--atr-purple)", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  prodRating: { display: "inline-flex", alignItems: "center", gap: 4, fontSize: 13, fontWeight: 700, color: "var(--atr-text)" },
  prodTitle: { fontSize: 16, fontWeight: 700, color: "var(--atr-text)", lineHeight: 1.3, letterSpacing: "-0.01em" },
  prodPrice: { fontSize: 18, fontWeight: 800, color: "var(--atr-red)", marginTop: "auto" },
  prodOpRow: { display: "flex", alignItems: "center", gap: 8, paddingTop: 10, borderTop: "1px solid var(--atr-outline)", marginTop: 4 },
  prodOpDot: { width: 24, height: 24, borderRadius: 999, background: "var(--atr-bg-cool)", flexShrink: 0, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontWeight: 800, color: "var(--atr-purple)" },
  prodOpName: { fontSize: 12.5, color: "var(--atr-text)", fontWeight: 600 },

  emptyWrap: { border: "2px dashed var(--atr-outline)", borderRadius: 16, padding: "56px 24px", textAlign: "center", marginTop: 24, background: "var(--atr-bg-soft)" },
  emptyIcon: { width: 72, height: 72, borderRadius: 999, background: "#fff", boxShadow: "var(--atr-shadow-2)", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "var(--atr-text-muted)", marginBottom: 18 },
  emptyTitle: { fontSize: 19, fontWeight: 700, color: "var(--atr-text)" },
  emptyText: { fontSize: 14, color: "var(--atr-text-muted)", marginTop: 8, maxWidth: 380, margin: "8px auto 0", lineHeight: 1.5 },

  /* move popover */
  popover: { position: "absolute", top: 52, right: 12, width: 250, background: "#fff", borderRadius: 14, boxShadow: "0 16px 40px rgba(31,27,51,0.25)", padding: 8, zIndex: 30, border: "1px solid var(--atr-outline)" },
  popHead: { fontSize: 11.5, fontWeight: 800, color: "var(--atr-text-muted)", textTransform: "uppercase", letterSpacing: "0.06em", padding: "10px 12px 6px" },
  popItem: { display: "flex", alignItems: "center", gap: 12, padding: "11px 12px", borderRadius: 9, cursor: "pointer", fontSize: 15, color: "var(--atr-text)", fontWeight: 600 },
  popCount: { marginLeft: "auto", color: "var(--atr-text-muted)", fontWeight: 700 },
  popDivider: { borderTop: "1px solid var(--atr-outline)", margin: "6px 4px" },
  popDelete: { display: "flex", alignItems: "center", gap: 12, padding: "11px 12px", borderRadius: 9, cursor: "pointer", fontSize: 15, color: "var(--atr-red)", fontWeight: 700, width: "100%", border: "none", background: "none", fontFamily: "var(--atr-font-sans)" },
};

export const revStyles = {
  toolbar: { display: "flex", alignItems: "center", gap: 12, marginTop: 22, flexWrap: "wrap" },
  filterLabel: { fontSize: 13.5, fontWeight: 600, color: "var(--atr-text-muted)" },
  fchip: { padding: "8px 18px", borderRadius: 999, fontSize: 13.5, fontWeight: 700, cursor: "pointer", border: "1px solid var(--atr-outline)", background: "#fff", color: "var(--atr-text)", fontFamily: "var(--atr-font-sans)" },
  fchipOn: { background: "var(--atr-purple)", color: "#fff", border: "1px solid var(--atr-purple)" },
  sortWrap: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 8 },

  card: { border: "1px solid var(--atr-outline)", borderRadius: 16, padding: 20, marginTop: 16, boxShadow: "var(--atr-shadow-1)", display: "flex", gap: 16 },
  thumb: { width: 84, height: 84, borderRadius: 12, objectFit: "cover", flexShrink: 0 },
  head: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
  prod: { fontSize: 15.5, fontWeight: 700, color: "var(--atr-text)" },
  loc: { fontSize: 12.5, color: "var(--atr-text-muted)", marginTop: 2, display: "inline-flex", alignItems: "center", gap: 5 },
  ratingBadge: { display: "inline-flex", alignItems: "center", gap: 5, background: "rgba(255,196,66,0.18)", color: "#9A6A00", padding: "5px 12px", borderRadius: 999, fontSize: 13, fontWeight: 800, whiteSpace: "nowrap" },
  text: { fontSize: 14, color: "var(--atr-text)", lineHeight: 1.55, marginTop: 10 },
  media: { display: "flex", gap: 8, marginTop: 12 },
  mediaImg: { width: 64, height: 64, borderRadius: 10, objectFit: "cover", border: "1px solid var(--atr-outline)" },
  foot: { display: "flex", alignItems: "center", gap: 14, marginTop: 14 },
  date: { fontSize: 12, color: "var(--atr-text-muted)" },
  helpful: { display: "inline-flex", alignItems: "center", gap: 7, background: "var(--atr-bg-soft)", border: "1px solid var(--atr-outline)", borderRadius: 999, padding: "7px 14px", fontSize: 13, fontWeight: 700, color: "var(--atr-text)", cursor: "pointer", fontFamily: "var(--atr-font-sans)" },
};

export const itinStyles = {
  grid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px,1fr))", gap: 20, marginTop: 22 },
  card: { border: "1px solid var(--atr-outline)", borderRadius: 16, background: "#fff", boxShadow: "var(--atr-shadow-1)", cursor: "pointer", display: "flex", flexDirection: "column", transition: "transform .15s, box-shadow .15s" },
  media: { position: "relative", height: 168, overflow: "hidden", borderTopLeftRadius: 16, borderTopRightRadius: 16 },
  img: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  scrim: { position: "absolute", inset: 0, background: "linear-gradient(180deg, rgba(31,27,51,0) 45%, rgba(31,27,51,0.42) 100%)" },
  tag: { position: "absolute", top: 12, left: 12, background: "rgba(255,255,255,0.92)", color: "var(--atr-text)", fontSize: 11.5, fontWeight: 800, padding: "5px 12px", borderRadius: 999 },
  pills: { position: "absolute", left: 12, bottom: 12, display: "flex", gap: 8, color: "#fff" },
  pill: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11.5, fontWeight: 700, background: "rgba(0,0,0,0.32)", backdropFilter: "blur(4px)", padding: "4px 10px", borderRadius: 999 },
  body: { padding: 16, display: "flex", flexDirection: "column", gap: 8, flex: 1 },
  title: { fontSize: 16, fontWeight: 700, color: "var(--atr-text)", lineHeight: 1.3, letterSpacing: "-0.01em" },
  foot: { display: "flex", alignItems: "center", justifyContent: "space-between", paddingTop: 12, borderTop: "1px solid var(--atr-outline)", marginTop: "auto" },
  author: { display: "flex", alignItems: "center", gap: 8 },
  avatar: { width: 26, height: 26, borderRadius: 999, background: "var(--atr-purple)", color: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 800 },
  role: { fontSize: 12, color: "var(--atr-text-muted)", fontWeight: 600 },
  price: { fontSize: 15, fontWeight: 800, color: "var(--atr-purple)" },
  tabs: { display: "flex", gap: 24, borderBottom: "1px solid var(--atr-outline)", marginTop: 18 },
  tab: { padding: "10px 2px 14px", fontSize: 14.5, fontWeight: 700, color: "var(--atr-text-muted)", cursor: "pointer", borderTop: "none", borderLeft: "none", borderRight: "none", borderBottom: "2px solid transparent", background: "none", fontFamily: "var(--atr-font-sans)", display: "inline-flex", alignItems: "center", gap: 7 },
  tabOn: { color: "var(--atr-purple)", borderBottom: "2px solid var(--atr-purple)" },
  tabCount: { fontSize: 12, fontWeight: 800, background: "var(--atr-bg-cool)", color: "var(--atr-purple)", borderRadius: 999, padding: "1px 8px" },

  /* MY itinerary (editable) */
  statusRow: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  badgeDraft: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11.5, fontWeight: 800, color: "#946400", background: "#FFF6E0", padding: "3px 10px", borderRadius: 999 },
  badgePub: { display: "inline-flex", alignItems: "center", gap: 5, fontSize: 11.5, fontWeight: 800, color: "#1F6B3B", background: "#ECF7F0", padding: "3px 10px", borderRadius: 999 },
  visMeta: { fontSize: 12, color: "var(--atr-text-muted)" },
  myFoot: { display: "flex", alignItems: "center", gap: 10, paddingTop: 12, borderTop: "1px solid var(--atr-outline)", marginTop: "auto" },
  editBtn: { flex: 1, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 7, padding: "9px 12px", borderRadius: 10, border: "1.5px solid var(--atr-purple)", background: "var(--atr-purple)", color: "#fff", fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)" },
  contBtn: { flex: 1, display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 7, padding: "9px 12px", borderRadius: 10, border: "1.5px solid var(--atr-outline)", background: "#fff", color: "var(--atr-text)", fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)" },
  iconBtn: { width: 38, flexShrink: 0, display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "9px 0", borderRadius: 10, borderWidth: "1.5px", borderStyle: "solid", borderColor: "var(--atr-outline)", background: "#fff", color: "var(--atr-text-muted)", cursor: "pointer" },
  newCard: { border: "1.5px dashed var(--atr-purple-light)", borderRadius: 16, background: "var(--atr-purple-50)", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", gap: 10, minHeight: 300, cursor: "pointer", color: "var(--atr-purple)", textAlign: "center", padding: 20, transition: "border-color .15s, background .15s" },
  newIcon: { width: 52, height: 52, borderRadius: 999, background: "#fff", display: "inline-flex", alignItems: "center", justifyContent: "center", color: "var(--atr-purple)", boxShadow: "var(--atr-shadow-1)" },
  newTitle: { fontSize: 15, fontWeight: 800, color: "var(--atr-text)" },
  newSub: { fontSize: 12.5, color: "var(--atr-text-muted)", maxWidth: 200, lineHeight: 1.5 },

  /* SAVED (read-only) */
  savedBadge: { position: "absolute", top: 12, right: 12, width: 34, height: 34, borderRadius: 999, background: "rgba(255,255,255,0.95)", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", boxShadow: "0 3px 10px rgba(0,0,0,0.16)", cursor: "pointer" },
  savedMeta: { fontSize: 12, color: "var(--atr-text-muted)", display: "inline-flex", alignItems: "center", gap: 5 },
  viewBtn: { display: "inline-flex", alignItems: "center", justifyContent: "center", gap: 6, padding: "8px 16px", borderRadius: 10, border: "1.5px solid var(--atr-outline)", background: "#fff", color: "var(--atr-purple)", fontSize: 13.5, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)" },

  /* dropdown menu */
  menuWrap: { position: "relative", flexShrink: 0 },
  menu: { position: "absolute", right: 0, bottom: "calc(100% + 8px)", width: 210, background: "#fff", borderRadius: 14, border: "1px solid var(--atr-outline)", boxShadow: "0 18px 44px rgba(31,27,51,0.18)", padding: 6, zIndex: 40, animation: "atrMenuPop .16s ease-out" },
  menuItem: { width: "100%", display: "flex", alignItems: "center", gap: 11, padding: "10px 12px", borderRadius: 9, border: "none", background: "transparent", fontSize: 13.5, fontWeight: 600, color: "var(--atr-text)", cursor: "pointer", fontFamily: "var(--atr-font-sans)", textAlign: "left" },
  menuItemDanger: { color: "var(--atr-red)" },
  menuDivider: { height: 1, background: "var(--atr-outline)", margin: "5px 4px" },
  menuScrim: { position: "fixed", inset: 0, zIndex: 30 },
};

export const insStyles = {
  head: { display: "flex", alignItems: "flex-start", gap: 14 },
  headIcon: { width: 44, height: 44, borderRadius: 12, background: "var(--atr-purple-50)", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },

  statGrid: { display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 14, marginTop: 22 },
  statCard: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: "16px 18px", display: "flex", alignItems: "center", gap: 14, background: "#fff", cursor: "pointer" },
  statCardOn: { border: "1px solid var(--atr-purple)", boxShadow: "0 0 0 1px var(--atr-purple)" },
  statIcon: { width: 40, height: 40, borderRadius: 11, display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, color: "#fff" },
  statLabel: { fontSize: 12, fontWeight: 700, color: "var(--atr-text-muted)", textTransform: "uppercase", letterSpacing: "0.04em" },
  statCount: { fontSize: 26, fontWeight: 800, color: "var(--atr-text)", lineHeight: 1, marginTop: 4 },

  row: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: "16px 20px", marginTop: 14, cursor: "pointer", display: "flex", alignItems: "center", gap: 16, boxShadow: "var(--atr-shadow-1)" },
  rowMain: { flex: 1, minWidth: 0 },
  rowTop: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 },
  code: { fontSize: 16, fontWeight: 800, color: "var(--atr-text)", letterSpacing: "0.02em" },
  grid: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16 },
  cellLabel: { fontSize: 12, color: "var(--atr-text-muted)" },
  cellVal: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)", marginTop: 3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },

  /* detail */
  detailHead: { display: "flex", alignItems: "center", gap: 10, cursor: "pointer", color: "var(--atr-text)", fontSize: 15, fontWeight: 700, marginBottom: 20 },
  summary: { border: "1px solid var(--atr-purple-light)", background: "linear-gradient(135deg, #F6F4FF 0%, #FAF9FF 100%)", borderRadius: 16, padding: 22 },
  sumTop: { display: "flex", alignItems: "center", gap: 14, marginBottom: 18 },
  sumIcon: { width: 48, height: 48, borderRadius: 13, background: "#fff", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, boxShadow: "var(--atr-shadow-1)" },
  sumCode: { fontSize: 26, fontWeight: 800, color: "var(--atr-text)", letterSpacing: "-0.01em" },
  polHead: { display: "flex", alignItems: "center", gap: 8, fontSize: 18, fontWeight: 700, color: "var(--atr-text)", margin: "26px 0 14px" },
  polCard: { border: "1px solid var(--atr-outline)", borderRadius: 16, overflow: "hidden" },
  polTop: { display: "flex", alignItems: "center", gap: 12, padding: "14px 20px", background: "var(--atr-bg-soft)", borderBottom: "1px solid var(--atr-outline)" },
  polNum: { width: 28, height: 28, borderRadius: 999, background: "var(--atr-purple-50)", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 13, fontWeight: 800, flexShrink: 0 },
  polName: { fontSize: 15.5, fontWeight: 700, color: "var(--atr-text)" },
  polPremi: { marginLeft: "auto", fontSize: 15, fontWeight: 800, color: "var(--atr-text)" },
  polGrid: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "20px 16px", padding: 20 },
};

export const kStyles = {
  detailHead: { display: "flex", alignItems: "center", gap: 10, cursor: "pointer", color: "var(--atr-text)", fontSize: 15, fontWeight: 700, marginBottom: 20 },
  headIcon: { width: 44, height: 44, borderRadius: 12, background: "var(--atr-purple-50)", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },

  stepper: { display: "flex", alignItems: "center", marginTop: 26 },
  stepItem: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  stepDot: { width: 30, height: 30, borderRadius: 999, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 13.5, fontWeight: 800, background: "var(--atr-bg-soft)", color: "var(--atr-text-muted)", border: "1.5px solid var(--atr-outline)" },
  stepDotOn: { background: "var(--atr-purple)", color: "#fff", border: "1.5px solid var(--atr-purple)" },
  stepDotDone: { background: "var(--atr-purple)", color: "#fff", border: "1.5px solid var(--atr-purple)" },
  stepLabel: { fontSize: 13, fontWeight: 700 },
  stepBar: { flex: 1, height: 2, margin: "0 12px", minWidth: 18 },

  qLabel: { fontSize: 16, fontWeight: 700, color: "var(--atr-text)" },
  typeCard: { display: "flex", alignItems: "flex-start", gap: 14, textAlign: "left", border: "1.5px solid var(--atr-outline)", borderRadius: 14, padding: "16px 18px", background: "#fff", cursor: "pointer", fontFamily: "var(--atr-font-sans)" },
  typeCardOn: { border: "1.5px solid var(--atr-purple)", background: "var(--atr-purple-50)" },
  radio: { width: 20, height: 20, borderRadius: 999, border: "2px solid var(--atr-outline)", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, marginTop: 1 },
  radioOn: { borderColor: "var(--atr-purple)" },
  radioInner: { width: 10, height: 10, borderRadius: 999, background: "var(--atr-purple)" },
  typeName: { display: "block", fontSize: 15, fontWeight: 700, color: "var(--atr-text)" },
  typeHint: { display: "block", fontSize: 13, color: "var(--atr-text-muted)", marginTop: 3, lineHeight: 1.4 },

  field: { display: "flex", flexDirection: "column", gap: 7 },
  helper: { fontSize: 12.5, color: "var(--atr-purple)", fontWeight: 700 },
  infoNote: { display: "flex", gap: 10, alignItems: "flex-start", background: "var(--atr-purple-50)", border: "1px solid var(--atr-purple-light)", borderRadius: 12, padding: "12px 16px", fontSize: 13, color: "var(--atr-text)", lineHeight: 1.45 },

  docRow: { display: "flex", alignItems: "center", gap: 14, border: "1px solid var(--atr-outline)", borderRadius: 12, padding: "14px 16px", background: "#fff" },
  docRowOn: { borderColor: "var(--atr-arti)", background: "rgba(81,176,84,0.06)" },
  docName: { display: "block", fontSize: 14, fontWeight: 700, color: "var(--atr-text)" },
  docFile: { display: "block", fontSize: 12, color: "var(--atr-arti)", marginTop: 2, fontWeight: 600 },
  uploadBtn: { display: "inline-flex", alignItems: "center", gap: 7, background: "var(--atr-purple-50)", color: "var(--atr-purple)", border: "1px solid var(--atr-purple-light)", borderRadius: 10, padding: "9px 14px", fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "var(--atr-font-sans)", flexShrink: 0 },

  review: { border: "1px solid var(--atr-outline)", borderRadius: 14, padding: 18, background: "var(--atr-bg-soft)" },
  reviewTitle: { fontSize: 14, fontWeight: 800, color: "var(--atr-text)", marginBottom: 12 },
  reviewRow: { display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 13.5, color: "var(--atr-text-muted)", padding: "7px 0", borderTop: "1px solid var(--atr-outline)" },

  formActions: { display: "flex", justifyContent: "space-between", gap: 12, marginTop: 28, paddingTop: 20, borderTop: "1px solid var(--atr-outline)" },

  summary: { border: "1px solid var(--atr-purple-light)", background: "linear-gradient(135deg, #F6F4FF 0%, #FAF9FF 100%)", borderRadius: 16, padding: 22 },
  sumIcon: { width: 48, height: 48, borderRadius: 13, background: "#fff", color: "var(--atr-purple)", display: "inline-flex", alignItems: "center", justifyContent: "center", flexShrink: 0, boxShadow: "var(--atr-shadow-1)" },
  sumGrid: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: "16px 16px" },
  cellLabel: { fontSize: 12, color: "var(--atr-text-muted)" },
  cellVal: { fontSize: 14, fontWeight: 700, color: "var(--atr-text)", marginTop: 3 },

  polHead: { display: "flex", alignItems: "center", gap: 8, fontSize: 18, fontWeight: 700, color: "var(--atr-text)", margin: "26px 0 18px" },
  timeline: { paddingLeft: 4 },
  tlRow: { display: "flex", gap: 16 },
  tlMarker: { display: "flex", flexDirection: "column", alignItems: "center", flexShrink: 0 },
  tlDot: { width: 32, height: 32, borderRadius: 999, display: "inline-flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 800, background: "var(--atr-bg-soft)", color: "var(--atr-text-muted)", border: "2px solid var(--atr-outline)" },
  tlDotOn: { background: "var(--atr-purple)", color: "#fff", border: "2px solid var(--atr-purple)" },
  tlDotActive: { background: "#fff", color: "var(--atr-purple)", border: "2px solid var(--atr-purple)", boxShadow: "0 0 0 4px var(--atr-purple-50)" },
  tlLine: { width: 2, flex: 1, marginTop: 4, marginBottom: 4, minHeight: 18 },
  tlNow: { display: "inline-block", marginTop: 8, fontSize: 12, fontWeight: 700, color: "var(--atr-purple)", background: "var(--atr-purple-50)", padding: "3px 10px", borderRadius: 999 },

  payout: { display: "flex", alignItems: "center", gap: 14, border: "1px solid rgba(81,176,84,0.35)", background: "rgba(81,176,84,0.06)", borderRadius: 14, padding: "16px 18px", marginTop: 22 },
};
