/* Utility bar styles */
const utilStyles = {
  bar: {
    width: '100%',
    fontFamily: 'var(--atr-font-sans)',
    fontSize: 12.5,
    borderBottom: '1px solid var(--atr-outline)',
  },
  barQuiet: { background: '#fff' },
  barSoft: { background: 'linear-gradient(180deg, #F6F4FF 0%, #FAF9FF 100%)' },
  inner: {
    maxWidth: 1376, margin: '0 auto', padding: '8px 32px',
    display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16,
  },
  promoSlot: {
    position: 'relative',
    display: 'inline-flex', alignItems: 'center', gap: 8,
    padding: '4px 0',
    cursor: 'pointer',
  },
  promoText: { color: 'var(--atr-text-muted)' },
  promoCta: {
    color: 'var(--atr-purple)', fontWeight: 700, textDecoration: 'none',
    display: 'inline-flex', alignItems: 'center', gap: 2,
    padding: '2px 8px', borderRadius: 999,
    transition: 'background .15s',
  },
  right: { display: 'inline-flex', alignItems: 'center', gap: 18 },
  utilLink: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    color: 'var(--atr-text)', fontSize: 12.5, fontWeight: 600,
    textDecoration: 'none',
    position: 'relative',
  },
  badge: {
    background: 'var(--atr-red)', color: '#fff',
    fontSize: 9, fontWeight: 700,
    padding: '1px 6px', borderRadius: 999, marginLeft: 2,
    minWidth: 16, textAlign: 'center',
  },
  mitraLink: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    color: 'var(--atr-purple)', fontSize: 12.5, fontWeight: 700,
    textDecoration: 'none',
    background: 'rgba(112,104,213,0.10)',
    border: '1px solid rgba(112,104,213,0.2)',
    padding: '4px 12px', borderRadius: 999,
  },
  divider: {
    display: 'inline-block',
    width: 1, height: 18,
    background: 'var(--atr-outline)',
  },
  localeBtnInline: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    background: 'transparent', border: 'none',
    color: 'var(--atr-text)', fontSize: 12.5, fontWeight: 600,
    cursor: 'pointer', fontFamily: 'var(--atr-font-sans)',
    padding: '4px 6px', borderRadius: 8,
  },
  localeMenu: {
    position: 'absolute', top: 'calc(100% + 8px)', right: 0,
    background: '#fff', border: '1px solid var(--atr-outline)',
    borderRadius: 10, padding: 4, boxShadow: '0 10px 28px rgba(31,27,51,0.12)',
    minWidth: 180, zIndex: 100, display: 'flex', flexDirection: 'column', gap: 2,
  },
  localeOpt: {
    background: 'transparent', border: 'none', textAlign: 'left',
    padding: '9px 12px', borderRadius: 6, cursor: 'pointer',
    fontSize: 13, color: 'var(--atr-text)', fontFamily: 'var(--atr-font-sans)',
    display: 'flex', alignItems: 'center', gap: 8,
  },
  localeOptActive: { background: 'var(--atr-bg-soft)', color: 'var(--atr-purple)', fontWeight: 700 },
  closeBtn: {
    width: 22, height: 22, borderRadius: 999,
    border: 'none', background: 'transparent',
    color: 'var(--atr-text-muted)', fontSize: 16, lineHeight: 1,
    cursor: 'pointer', display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    fontFamily: 'var(--atr-font-sans)',
  },
  pop: {
    position: 'absolute',
    top: 'calc(100% + 10px)', left: -16,
    width: 280,
    background: '#fff',
    border: '1px solid var(--atr-outline)',
    borderRadius: 14,
    boxShadow: '0 24px 60px rgba(31,27,51,0.18)',
    overflow: 'hidden',
    zIndex: 200,
    cursor: 'default',
  },
  popHead: {
    background: 'var(--atr-purple)',
    color: '#fff',
    padding: '10px 14px 14px',
    fontSize: 12.5, fontWeight: 500,
    display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 8,
    borderRadius: '14px 14px 16px 16px',
  },
  popClose: {
    width: 22, height: 22, borderRadius: 999,
    border: 'none', background: 'rgba(255,255,255,0.2)',
    color: '#fff', fontSize: 14, cursor: 'pointer',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
  },
  popBody: { padding: '18px 18px 20px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, marginTop: -6, background: '#fff', borderRadius: '16px 16px 14px 14px' },
  popTitle: { fontSize: 14, fontWeight: 700, color: 'var(--atr-text)', textAlign: 'center', lineHeight: 1.4 },
  popSub: { fontSize: 12.5, color: 'var(--atr-text-muted)', textAlign: 'center' },
  qrFrame: {
    margin: '8px 0',
    padding: 6, borderRadius: 12,
    background: '#fff', border: '1px solid var(--atr-outline)',
    width: 168, height: 168,
    display: 'flex', alignItems: 'center', justifyContent: 'center',
  },
  qrImg: { width: '100%', height: '100%', objectFit: 'contain', display: 'block' },
  popOr: { fontSize: 11.5, color: 'var(--atr-text-muted)', marginTop: 4 },
  storeCol: { display: 'flex', flexDirection: 'column', gap: 8, width: 168, marginTop: 4 },
  storeBtn: {
    background: '#1F1B33', color: '#fff', borderRadius: 8,
    padding: '8px 14px', display: 'inline-flex', alignItems: 'center', gap: 10,
    textDecoration: 'none', fontFamily: 'var(--atr-font-sans)',
  },
  storeText: { display: 'flex', flexDirection: 'column', lineHeight: 1.2 },
  avatarBtn: {
    background: 'transparent', border: '1px solid var(--atr-outline)',
    borderRadius: 999, padding: '4px 12px 4px 4px',
    display: 'inline-flex', alignItems: 'center', gap: 8,
    cursor: 'pointer', fontFamily: 'var(--atr-font-sans)',
  },
  bellBtn: {
    position: 'relative', width: 40, height: 40, borderRadius: 999, flexShrink: 0,
    border: '1px solid var(--atr-outline)', background: '#fff',
    color: 'var(--atr-text)', textDecoration: 'none',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    transition: 'background .12s, border-color .12s',
  },
  bellBadge: {
    position: 'absolute', top: -3, right: -3,
    minWidth: 18, height: 18, padding: '0 5px', borderRadius: 999,
    background: 'var(--atr-red)', color: '#fff', border: '2px solid #fff',
    fontSize: 10, fontWeight: 800, lineHeight: '14px',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
  },
  avatar: {
    width: 30, height: 30, borderRadius: 999,
    background: 'linear-gradient(135deg, var(--atr-purple) 0%, #9b6aab 100%)',
    color: '#fff', fontWeight: 700, fontSize: 13,
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
  },
  userMenu: {
    position: 'absolute', top: 'calc(100% + 10px)', right: 0,
    background: '#fff', border: '1px solid var(--atr-outline)',
    borderRadius: 16, padding: 8, boxShadow: '0 16px 40px rgba(31,27,51,0.16)',
    width: 268, zIndex: 200, display: 'flex', flexDirection: 'column',
  },
  userMenuScrim: { position: 'fixed', inset: 0, zIndex: 150, background: 'transparent' },
  userMenuHeader: {
    display: 'flex', alignItems: 'center', gap: 12,
    padding: '10px 12px 14px',
  },
  userMenuAvatar: {
    width: 44, height: 44, borderRadius: 999, flexShrink: 0,
    background: 'linear-gradient(135deg, var(--atr-purple) 0%, #9b6aab 100%)',
    color: '#fff', fontWeight: 700, fontSize: 18,
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
  },
  userMenuHello: { fontSize: 11.5, color: 'var(--atr-text-muted)', fontWeight: 500 },
  userMenuName: { fontSize: 15, fontWeight: 700, color: 'var(--atr-text)', lineHeight: 1.2, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  userMenuEmail: { fontSize: 12, color: 'var(--atr-text-muted)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', marginTop: 1 },
  userMenuList: {
    display: 'flex', flexDirection: 'column', gap: 2,
    borderTop: '1px solid var(--atr-outline)', paddingTop: 6,
  },
  userMenuItem: {
    padding: '9px 12px', borderRadius: 10,
    fontSize: 13.5, fontWeight: 600, color: 'var(--atr-text)', textDecoration: 'none',
    display: 'flex', alignItems: 'center', gap: 12,
    cursor: 'pointer', whiteSpace: 'nowrap',
  },
  userMenuIcon: {
    width: 32, height: 32, borderRadius: 999, flexShrink: 0,
    border: '1px solid var(--atr-outline)', background: '#fff',
    color: 'var(--atr-text-muted)',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    transition: 'border-color .12s, color .12s',
  },
  userMenuIconLogout: { border: '1px solid rgba(244,98,99,0.3)', color: 'var(--atr-red)', background: 'rgba(244,98,99,0.06)' },
  userMenuItemLabel: { flex: 1 },
  userMenuTag: {
    fontSize: 9.5, fontWeight: 800, letterSpacing: '0.04em',
    color: 'var(--atr-purple)', background: 'var(--atr-purple-50)',
    border: '1px solid var(--atr-purple-light)',
    padding: '2px 7px', borderRadius: 999, textTransform: 'uppercase',
  },
  userMenuLogout: { color: 'var(--atr-red)' },
  userMenuDivider: { height: 1, background: 'var(--atr-outline)', margin: '6px 4px' },
};

export default utilStyles;
